-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    layer7_out_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer7_out_0_ap_vld : OUT STD_LOGIC;
    layer7_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer7_out_1_ap_vld : OUT STD_LOGIC;
    layer7_out_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer7_out_2_ap_vld : OUT STD_LOGIC;
    layer7_out_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer7_out_3_ap_vld : OUT STD_LOGIC;
    layer7_out_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer7_out_4_ap_vld : OUT STD_LOGIC;
    layer7_out_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer7_out_5_ap_vld : OUT STD_LOGIC );
end;


architecture behav of myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q1 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q2 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q3 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q4 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address5 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q5 : STD_LOGIC_VECTOR (10 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_read_1_reg_667 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read_2_reg_672 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_fu_238_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_reg_677 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_1_fu_258_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_1_reg_682 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_2_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_2_reg_687 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_reg_692 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln248_fu_278_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_reg_697 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_1_fu_282_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_1_reg_702 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_2_fu_286_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_2_reg_707 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_3_fu_290_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_3_reg_712 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_4_fu_294_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_4_reg_717 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_5_fu_298_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_5_reg_722 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_6_reg_742 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_load_reg_757 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_reg_757_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_1_reg_763 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_1_reg_763_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_2_reg_769 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_2_reg_769_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_4_reg_780 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_4_reg_780_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_5_reg_786 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_5_reg_786_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_3_reg_792 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln258_fu_392_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln258_1_fu_407_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_2_fu_422_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_4_fu_447_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_5_fu_462_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_3_fu_467_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln267_fu_538_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal layer7_out_0_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal layer7_out_1_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer7_out_2_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer7_out_3_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer7_out_4_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer7_out_5_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal exp_table_ce5_local : STD_LOGIC;
    signal exp_table_ce4_local : STD_LOGIC;
    signal exp_table_ce3_local : STD_LOGIC;
    signal exp_table_ce2_local : STD_LOGIC;
    signal exp_table_ce1_local : STD_LOGIC;
    signal exp_table_ce0_local : STD_LOGIC;
    signal invert_table_ce0_local : STD_LOGIC;
    signal icmp_ln66_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_1_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_2_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_3_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_2_fu_307_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_3_fu_318_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_4_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_4_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_fu_336_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln66_1_fu_340_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln66_4_fu_344_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_fu_352_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_382_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_1_fu_357_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_2_fu_397_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_2_fu_362_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_4_fu_412_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_3_fu_367_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_4_fu_372_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_8_fu_437_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_5_fu_377_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_452_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln145_fu_471_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln145_2_fu_477_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_fu_490_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln145_1_fu_474_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_1_fu_496_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_1_fu_502_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln145_3_fu_480_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln145_4_fu_484_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_fu_487_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_3_fu_512_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_2_fu_518_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln51_2_fu_506_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln51_4_fu_522_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_528_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln270_fu_550_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln270_fu_543_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_fu_550_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln270_fu_550_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_1_fu_570_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_1_fu_570_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln270_1_fu_570_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_2_fu_590_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_2_fu_590_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln270_2_fu_590_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_3_fu_610_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_3_fu_610_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln270_3_fu_610_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_4_fu_630_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_4_fu_630_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln270_4_fu_630_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_5_fu_650_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_5_fu_650_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln270_5_fu_650_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal mul_ln270_1_fu_570_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_2_fu_590_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_3_fu_610_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_4_fu_630_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_5_fu_650_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_fu_550_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_18s_11ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_exp_table_ROM_Abkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address5 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_invert_table_ROcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_exp_table_ROM_Abkb
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0_local,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1_local,
        q1 => exp_table_q1,
        address2 => exp_table_address2,
        ce2 => exp_table_ce2_local,
        q2 => exp_table_q2,
        address3 => exp_table_address3,
        ce3 => exp_table_ce3_local,
        q3 => exp_table_q3,
        address4 => exp_table_address4,
        ce4 => exp_table_ce4_local,
        q4 => exp_table_q4,
        address5 => exp_table_address5,
        ce5 => exp_table_ce5_local,
        q5 => exp_table_q5);

    invert_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_invert_table_ROcud
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0_local,
        q0 => invert_table_q0);

    mul_18s_11ns_26_1_1_U4736 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln270_fu_550_p0,
        din1 => mul_ln270_fu_550_p1,
        dout => mul_ln270_fu_550_p2);

    mul_18s_11ns_26_1_1_U4737 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln270_1_fu_570_p0,
        din1 => mul_ln270_1_fu_570_p1,
        dout => mul_ln270_1_fu_570_p2);

    mul_18s_11ns_26_1_1_U4738 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln270_2_fu_590_p0,
        din1 => mul_ln270_2_fu_590_p1,
        dout => mul_ln270_2_fu_590_p2);

    mul_18s_11ns_26_1_1_U4739 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln270_3_fu_610_p0,
        din1 => mul_ln270_3_fu_610_p1,
        dout => mul_ln270_3_fu_610_p2);

    mul_18s_11ns_26_1_1_U4740 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln270_4_fu_630_p0,
        din1 => mul_ln270_4_fu_630_p1,
        dout => mul_ln270_4_fu_630_p2);

    mul_18s_11ns_26_1_1_U4741 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln270_5_fu_650_p0,
        din1 => mul_ln270_5_fu_650_p1,
        dout => mul_ln270_5_fu_650_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    layer7_out_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer7_out_0_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                    layer7_out_0_preg <= mul_ln270_fu_550_p2(25 downto 10);
                end if; 
            end if;
        end if;
    end process;


    layer7_out_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer7_out_1_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                    layer7_out_1_preg <= mul_ln270_1_fu_570_p2(25 downto 10);
                end if; 
            end if;
        end if;
    end process;


    layer7_out_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer7_out_2_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                    layer7_out_2_preg <= mul_ln270_2_fu_590_p2(25 downto 10);
                end if; 
            end if;
        end if;
    end process;


    layer7_out_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer7_out_3_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                    layer7_out_3_preg <= mul_ln270_3_fu_610_p2(25 downto 10);
                end if; 
            end if;
        end if;
    end process;


    layer7_out_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer7_out_4_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                    layer7_out_4_preg <= mul_ln270_4_fu_630_p2(25 downto 10);
                end if; 
            end if;
        end if;
    end process;


    layer7_out_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer7_out_5_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                    layer7_out_5_preg <= mul_ln270_5_fu_650_p2(25 downto 10);
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                exp_table_load_1_reg_763 <= exp_table_q4;
                exp_table_load_2_reg_769 <= exp_table_q3;
                exp_table_load_4_reg_780 <= exp_table_q2;
                exp_table_load_5_reg_786 <= exp_table_q1;
                exp_table_load_reg_757 <= exp_table_q5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                exp_table_load_1_reg_763_pp0_iter3_reg <= exp_table_load_1_reg_763;
                exp_table_load_2_reg_769_pp0_iter3_reg <= exp_table_load_2_reg_769;
                exp_table_load_4_reg_780_pp0_iter3_reg <= exp_table_load_4_reg_780;
                exp_table_load_5_reg_786_pp0_iter3_reg <= exp_table_load_5_reg_786;
                exp_table_load_reg_757_pp0_iter3_reg <= exp_table_load_reg_757;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                exp_table_load_3_reg_792 <= exp_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln66_2_reg_687 <= icmp_ln66_2_fu_266_p2;
                icmp_ln66_3_reg_692 <= icmp_ln66_3_fu_272_p2;
                p_read_1_reg_667 <= p_read5;
                p_read_2_reg_672 <= p_read4;
                select_ln66_1_reg_682 <= select_ln66_1_fu_258_p3;
                select_ln66_reg_677 <= select_ln66_fu_238_p3;
                tmp_6_reg_742 <= d_xi_xmax_3_fu_367_p2(14 downto 5);
                trunc_ln248_1_reg_702 <= trunc_ln248_1_fu_282_p1;
                trunc_ln248_2_reg_707 <= trunc_ln248_2_fu_286_p1;
                trunc_ln248_3_reg_712 <= trunc_ln248_3_fu_290_p1;
                trunc_ln248_4_reg_717 <= trunc_ln248_4_fu_294_p1;
                trunc_ln248_5_reg_722 <= trunc_ln248_5_fu_298_p1;
                trunc_ln248_reg_697 <= trunc_ln248_fu_278_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln51_1_fu_496_p2 <= std_logic_vector(unsigned(add_ln51_fu_490_p2) + unsigned(zext_ln145_1_fu_474_p1));
    add_ln51_2_fu_506_p2 <= std_logic_vector(unsigned(zext_ln51_1_fu_502_p1) + unsigned(zext_ln145_3_fu_480_p1));
    add_ln51_3_fu_512_p2 <= std_logic_vector(unsigned(zext_ln145_4_fu_484_p1) + unsigned(zext_ln51_fu_487_p1));
    add_ln51_4_fu_522_p2 <= std_logic_vector(unsigned(zext_ln51_2_fu_518_p1) + unsigned(add_ln51_2_fu_506_p2));
    add_ln51_fu_490_p2 <= std_logic_vector(unsigned(zext_ln145_fu_471_p1) + unsigned(zext_ln145_2_fu_477_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter4, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to3)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    d_xi_xmax_1_fu_357_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_344_p3) - unsigned(trunc_ln248_1_reg_702));
    d_xi_xmax_2_fu_362_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_344_p3) - unsigned(trunc_ln248_2_reg_707));
    d_xi_xmax_3_fu_367_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_344_p3) - unsigned(trunc_ln248_3_reg_712));
    d_xi_xmax_4_fu_372_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_344_p3) - unsigned(trunc_ln248_4_reg_717));
    d_xi_xmax_5_fu_377_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_344_p3) - unsigned(trunc_ln248_5_reg_722));
    d_xi_xmax_fu_352_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_344_p3) - unsigned(trunc_ln248_reg_697));
    exp_table_address0 <= zext_ln258_3_fu_467_p1(10 - 1 downto 0);
    exp_table_address1 <= zext_ln258_5_fu_462_p1(10 - 1 downto 0);
    exp_table_address2 <= zext_ln258_4_fu_447_p1(10 - 1 downto 0);
    exp_table_address3 <= zext_ln258_2_fu_422_p1(10 - 1 downto 0);
    exp_table_address4 <= zext_ln258_1_fu_407_p1(10 - 1 downto 0);
    exp_table_address5 <= zext_ln258_fu_392_p1(10 - 1 downto 0);

    exp_table_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            exp_table_ce0_local <= ap_const_logic_1;
        else 
            exp_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce1_local <= ap_const_logic_1;
        else 
            exp_table_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce2_local <= ap_const_logic_1;
        else 
            exp_table_ce2_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce3_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce3_local <= ap_const_logic_1;
        else 
            exp_table_ce3_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce4_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce4_local <= ap_const_logic_1;
        else 
            exp_table_ce4_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce5_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce5_local <= ap_const_logic_1;
        else 
            exp_table_ce5_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln66_1_fu_246_p2 <= "1" when (signed(p_read2) < signed(p_read3)) else "0";
    icmp_ln66_2_fu_266_p2 <= "1" when (signed(select_ln66_fu_238_p3) < signed(select_ln66_1_fu_258_p3)) else "0";
    icmp_ln66_3_fu_272_p2 <= "1" when (signed(p_read4) < signed(p_read5)) else "0";
    icmp_ln66_4_fu_324_p2 <= "1" when (signed(select_ln66_2_fu_307_p3) < signed(select_ln66_3_fu_318_p3)) else "0";
    icmp_ln66_fu_226_p2 <= "1" when (signed(p_read) < signed(p_read1)) else "0";
    invert_table_address0 <= zext_ln267_fu_538_p1(10 - 1 downto 0);

    invert_table_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            invert_table_ce0_local <= ap_const_logic_1;
        else 
            invert_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_0_assign_proc : process(ap_enable_reg_pp0_iter4, layer7_out_0_preg, ap_block_pp0_stage0_01001, mul_ln270_fu_550_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_0 <= mul_ln270_fu_550_p2(25 downto 10);
        else 
            layer7_out_0 <= layer7_out_0_preg;
        end if; 
    end process;


    layer7_out_0_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_0_ap_vld <= ap_const_logic_1;
        else 
            layer7_out_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_01001, layer7_out_1_preg, mul_ln270_1_fu_570_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_1 <= mul_ln270_1_fu_570_p2(25 downto 10);
        else 
            layer7_out_1 <= layer7_out_1_preg;
        end if; 
    end process;


    layer7_out_1_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_1_ap_vld <= ap_const_logic_1;
        else 
            layer7_out_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_2_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_01001, layer7_out_2_preg, mul_ln270_2_fu_590_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_2 <= mul_ln270_2_fu_590_p2(25 downto 10);
        else 
            layer7_out_2 <= layer7_out_2_preg;
        end if; 
    end process;


    layer7_out_2_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_2_ap_vld <= ap_const_logic_1;
        else 
            layer7_out_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_3_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_01001, layer7_out_3_preg, mul_ln270_3_fu_610_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_3 <= mul_ln270_3_fu_610_p2(25 downto 10);
        else 
            layer7_out_3 <= layer7_out_3_preg;
        end if; 
    end process;


    layer7_out_3_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_3_ap_vld <= ap_const_logic_1;
        else 
            layer7_out_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_4_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_01001, layer7_out_4_preg, mul_ln270_4_fu_630_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_4 <= mul_ln270_4_fu_630_p2(25 downto 10);
        else 
            layer7_out_4 <= layer7_out_4_preg;
        end if; 
    end process;


    layer7_out_4_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_4_ap_vld <= ap_const_logic_1;
        else 
            layer7_out_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_5_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_01001, layer7_out_5_preg, mul_ln270_5_fu_650_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_5 <= mul_ln270_5_fu_650_p2(25 downto 10);
        else 
            layer7_out_5 <= layer7_out_5_preg;
        end if; 
    end process;


    layer7_out_5_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer7_out_5_ap_vld <= ap_const_logic_1;
        else 
            layer7_out_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln270_1_fu_570_p0 <= sext_ln270_fu_543_p1(18 - 1 downto 0);
    mul_ln270_1_fu_570_p1 <= mul_ln270_1_fu_570_p10(11 - 1 downto 0);
    mul_ln270_1_fu_570_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_1_reg_763_pp0_iter3_reg),26));
    mul_ln270_2_fu_590_p0 <= sext_ln270_fu_543_p1(18 - 1 downto 0);
    mul_ln270_2_fu_590_p1 <= mul_ln270_2_fu_590_p10(11 - 1 downto 0);
    mul_ln270_2_fu_590_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_2_reg_769_pp0_iter3_reg),26));
    mul_ln270_3_fu_610_p0 <= sext_ln270_fu_543_p1(18 - 1 downto 0);
    mul_ln270_3_fu_610_p1 <= mul_ln270_3_fu_610_p10(11 - 1 downto 0);
    mul_ln270_3_fu_610_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_3_reg_792),26));
    mul_ln270_4_fu_630_p0 <= sext_ln270_fu_543_p1(18 - 1 downto 0);
    mul_ln270_4_fu_630_p1 <= mul_ln270_4_fu_630_p10(11 - 1 downto 0);
    mul_ln270_4_fu_630_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_4_reg_780_pp0_iter3_reg),26));
    mul_ln270_5_fu_650_p0 <= sext_ln270_fu_543_p1(18 - 1 downto 0);
    mul_ln270_5_fu_650_p1 <= mul_ln270_5_fu_650_p10(11 - 1 downto 0);
    mul_ln270_5_fu_650_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_5_reg_786_pp0_iter3_reg),26));
    mul_ln270_fu_550_p0 <= sext_ln270_fu_543_p1(18 - 1 downto 0);
    mul_ln270_fu_550_p1 <= mul_ln270_fu_550_p10(11 - 1 downto 0);
    mul_ln270_fu_550_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_reg_757_pp0_iter3_reg),26));
    select_ln66_1_fu_258_p3 <= 
        p_read2 when (xor_ln66_1_fu_252_p2(0) = '1') else 
        p_read3;
    select_ln66_2_fu_307_p3 <= 
        select_ln66_reg_677 when (xor_ln66_2_fu_302_p2(0) = '1') else 
        select_ln66_1_reg_682;
    select_ln66_3_fu_318_p3 <= 
        p_read_2_reg_672 when (xor_ln66_3_fu_313_p2(0) = '1') else 
        p_read_1_reg_667;
    select_ln66_4_fu_344_p3 <= 
        trunc_ln66_fu_336_p1 when (xor_ln66_4_fu_330_p2(0) = '1') else 
        trunc_ln66_1_fu_340_p1;
    select_ln66_fu_238_p3 <= 
        p_read when (xor_ln66_fu_232_p2(0) = '1') else 
        p_read1;
        sext_ln270_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(invert_table_q0),26));

    tmp_1_fu_528_p4 <= add_ln51_4_fu_522_p2(12 downto 8);
    tmp_2_fu_397_p4 <= d_xi_xmax_1_fu_357_p2(14 downto 5);
    tmp_4_fu_412_p4 <= d_xi_xmax_2_fu_362_p2(14 downto 5);
    tmp_8_fu_437_p4 <= d_xi_xmax_4_fu_372_p2(14 downto 5);
    tmp_fu_382_p4 <= d_xi_xmax_fu_352_p2(14 downto 5);
    tmp_s_fu_452_p4 <= d_xi_xmax_5_fu_377_p2(14 downto 5);
    trunc_ln248_1_fu_282_p1 <= p_read1(15 - 1 downto 0);
    trunc_ln248_2_fu_286_p1 <= p_read2(15 - 1 downto 0);
    trunc_ln248_3_fu_290_p1 <= p_read3(15 - 1 downto 0);
    trunc_ln248_4_fu_294_p1 <= p_read4(15 - 1 downto 0);
    trunc_ln248_5_fu_298_p1 <= p_read5(15 - 1 downto 0);
    trunc_ln248_fu_278_p1 <= p_read(15 - 1 downto 0);
    trunc_ln66_1_fu_340_p1 <= select_ln66_3_fu_318_p3(15 - 1 downto 0);
    trunc_ln66_fu_336_p1 <= select_ln66_2_fu_307_p3(15 - 1 downto 0);
    xor_ln66_1_fu_252_p2 <= (icmp_ln66_1_fu_246_p2 xor ap_const_lv1_1);
    xor_ln66_2_fu_302_p2 <= (icmp_ln66_2_reg_687 xor ap_const_lv1_1);
    xor_ln66_3_fu_313_p2 <= (icmp_ln66_3_reg_692 xor ap_const_lv1_1);
    xor_ln66_4_fu_330_p2 <= (icmp_ln66_4_fu_324_p2 xor ap_const_lv1_1);
    xor_ln66_fu_232_p2 <= (icmp_ln66_fu_226_p2 xor ap_const_lv1_1);
    zext_ln145_1_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_1_reg_763),12));
    zext_ln145_2_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_2_reg_769),12));
    zext_ln145_3_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q0),13));
    zext_ln145_4_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_4_reg_780),12));
    zext_ln145_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_reg_757),12));
    zext_ln258_1_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_397_p4),64));
    zext_ln258_2_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_412_p4),64));
    zext_ln258_3_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_reg_742),64));
    zext_ln258_4_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_437_p4),64));
    zext_ln258_5_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_452_p4),64));
    zext_ln258_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_382_p4),64));
    zext_ln267_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_528_p4),64));
    zext_ln51_1_fu_502_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln51_1_fu_496_p2),13));
    zext_ln51_2_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln51_3_fu_512_p2),13));
    zext_ln51_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_5_reg_786),12));
end behav;
