Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
InputShapes:
  input_5:
  - 128
  - 9
KerasModel: !keras_model 'model_1/hls4ml_prj/keras_model.keras'
OutputDir: model_1/hls4ml_prj
OutputPredictions: null
OutputShapes:
  layer7_out:
  - 6
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 083df197
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
