// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        layer7_out_0,
        layer7_out_0_ap_vld,
        layer7_out_1,
        layer7_out_1_ap_vld,
        layer7_out_2,
        layer7_out_2_ap_vld,
        layer7_out_3,
        layer7_out_3_ap_vld,
        layer7_out_4,
        layer7_out_4_ap_vld,
        layer7_out_5,
        layer7_out_5_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
output  [15:0] layer7_out_0;
output   layer7_out_0_ap_vld;
output  [15:0] layer7_out_1;
output   layer7_out_1_ap_vld;
output  [15:0] layer7_out_2;
output   layer7_out_2_ap_vld;
output  [15:0] layer7_out_3;
output   layer7_out_3_ap_vld;
output  [15:0] layer7_out_4;
output   layer7_out_4_ap_vld;
output  [15:0] layer7_out_5;
output   layer7_out_5_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] layer7_out_0;
reg layer7_out_0_ap_vld;
reg[15:0] layer7_out_1;
reg layer7_out_1_ap_vld;
reg[15:0] layer7_out_2;
reg layer7_out_2_ap_vld;
reg[15:0] layer7_out_3;
reg layer7_out_3_ap_vld;
reg[15:0] layer7_out_4;
reg layer7_out_4_ap_vld;
reg[15:0] layer7_out_5;
reg layer7_out_5_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [9:0] exp_table_address0;
wire   [10:0] exp_table_q0;
wire   [9:0] exp_table_address1;
wire   [10:0] exp_table_q1;
wire   [9:0] exp_table_address2;
wire   [10:0] exp_table_q2;
wire   [9:0] exp_table_address3;
wire   [10:0] exp_table_q3;
wire   [9:0] exp_table_address4;
wire   [10:0] exp_table_q4;
wire   [9:0] exp_table_address5;
wire   [10:0] exp_table_q5;
wire   [9:0] invert_table_address0;
wire   [17:0] invert_table_q0;
reg   [15:0] p_read_1_reg_667;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] p_read_2_reg_672;
wire   [15:0] select_ln66_fu_238_p3;
reg   [15:0] select_ln66_reg_677;
wire   [15:0] select_ln66_1_fu_258_p3;
reg   [15:0] select_ln66_1_reg_682;
wire   [0:0] icmp_ln66_2_fu_266_p2;
reg   [0:0] icmp_ln66_2_reg_687;
wire   [0:0] icmp_ln66_3_fu_272_p2;
reg   [0:0] icmp_ln66_3_reg_692;
wire   [14:0] trunc_ln248_fu_278_p1;
reg   [14:0] trunc_ln248_reg_697;
wire   [14:0] trunc_ln248_1_fu_282_p1;
reg   [14:0] trunc_ln248_1_reg_702;
wire   [14:0] trunc_ln248_2_fu_286_p1;
reg   [14:0] trunc_ln248_2_reg_707;
wire   [14:0] trunc_ln248_3_fu_290_p1;
reg   [14:0] trunc_ln248_3_reg_712;
wire   [14:0] trunc_ln248_4_fu_294_p1;
reg   [14:0] trunc_ln248_4_reg_717;
wire   [14:0] trunc_ln248_5_fu_298_p1;
reg   [14:0] trunc_ln248_5_reg_722;
reg   [9:0] tmp_6_reg_742;
reg   [10:0] exp_table_load_reg_757;
reg   [10:0] exp_table_load_reg_757_pp0_iter3_reg;
reg   [10:0] exp_table_load_1_reg_763;
reg   [10:0] exp_table_load_1_reg_763_pp0_iter3_reg;
reg   [10:0] exp_table_load_2_reg_769;
reg   [10:0] exp_table_load_2_reg_769_pp0_iter3_reg;
reg   [10:0] exp_table_load_4_reg_780;
reg   [10:0] exp_table_load_4_reg_780_pp0_iter3_reg;
reg   [10:0] exp_table_load_5_reg_786;
reg   [10:0] exp_table_load_5_reg_786_pp0_iter3_reg;
reg   [10:0] exp_table_load_3_reg_792;
wire   [63:0] zext_ln258_fu_392_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln258_1_fu_407_p1;
wire   [63:0] zext_ln258_2_fu_422_p1;
wire   [63:0] zext_ln258_4_fu_447_p1;
wire   [63:0] zext_ln258_5_fu_462_p1;
wire   [63:0] zext_ln258_3_fu_467_p1;
wire   [63:0] zext_ln267_fu_538_p1;
reg   [15:0] layer7_out_0_preg;
reg    ap_block_pp0_stage0_01001;
reg   [15:0] layer7_out_1_preg;
reg   [15:0] layer7_out_2_preg;
reg   [15:0] layer7_out_3_preg;
reg   [15:0] layer7_out_4_preg;
reg   [15:0] layer7_out_5_preg;
reg    exp_table_ce5_local;
reg    exp_table_ce4_local;
reg    exp_table_ce3_local;
reg    exp_table_ce2_local;
reg    exp_table_ce1_local;
reg    exp_table_ce0_local;
reg    invert_table_ce0_local;
wire   [0:0] icmp_ln66_fu_226_p2;
wire   [0:0] xor_ln66_fu_232_p2;
wire   [0:0] icmp_ln66_1_fu_246_p2;
wire   [0:0] xor_ln66_1_fu_252_p2;
wire   [0:0] xor_ln66_2_fu_302_p2;
wire   [0:0] xor_ln66_3_fu_313_p2;
wire   [15:0] select_ln66_2_fu_307_p3;
wire   [15:0] select_ln66_3_fu_318_p3;
wire   [0:0] icmp_ln66_4_fu_324_p2;
wire   [0:0] xor_ln66_4_fu_330_p2;
wire   [14:0] trunc_ln66_fu_336_p1;
wire   [14:0] trunc_ln66_1_fu_340_p1;
wire   [14:0] select_ln66_4_fu_344_p3;
wire   [14:0] d_xi_xmax_fu_352_p2;
wire   [9:0] tmp_fu_382_p4;
wire   [14:0] d_xi_xmax_1_fu_357_p2;
wire   [9:0] tmp_2_fu_397_p4;
wire   [14:0] d_xi_xmax_2_fu_362_p2;
wire   [9:0] tmp_4_fu_412_p4;
wire   [14:0] d_xi_xmax_3_fu_367_p2;
wire   [14:0] d_xi_xmax_4_fu_372_p2;
wire   [9:0] tmp_8_fu_437_p4;
wire   [14:0] d_xi_xmax_5_fu_377_p2;
wire   [9:0] tmp_s_fu_452_p4;
wire   [11:0] zext_ln145_fu_471_p1;
wire   [11:0] zext_ln145_2_fu_477_p1;
wire   [11:0] add_ln51_fu_490_p2;
wire   [11:0] zext_ln145_1_fu_474_p1;
wire   [11:0] add_ln51_1_fu_496_p2;
wire   [12:0] zext_ln51_1_fu_502_p1;
wire   [12:0] zext_ln145_3_fu_480_p1;
wire   [11:0] zext_ln145_4_fu_484_p1;
wire   [11:0] zext_ln51_fu_487_p1;
wire   [11:0] add_ln51_3_fu_512_p2;
wire   [12:0] zext_ln51_2_fu_518_p1;
wire   [12:0] add_ln51_2_fu_506_p2;
wire   [12:0] add_ln51_4_fu_522_p2;
wire   [4:0] tmp_1_fu_528_p4;
wire  signed [17:0] mul_ln270_fu_550_p0;
wire  signed [25:0] sext_ln270_fu_543_p1;
wire   [10:0] mul_ln270_fu_550_p1;
wire   [25:0] mul_ln270_fu_550_p2;
wire  signed [17:0] mul_ln270_1_fu_570_p0;
wire   [10:0] mul_ln270_1_fu_570_p1;
wire   [25:0] mul_ln270_1_fu_570_p2;
wire  signed [17:0] mul_ln270_2_fu_590_p0;
wire   [10:0] mul_ln270_2_fu_590_p1;
wire   [25:0] mul_ln270_2_fu_590_p2;
wire  signed [17:0] mul_ln270_3_fu_610_p0;
wire   [10:0] mul_ln270_3_fu_610_p1;
wire   [25:0] mul_ln270_3_fu_610_p2;
wire  signed [17:0] mul_ln270_4_fu_630_p0;
wire   [10:0] mul_ln270_4_fu_630_p1;
wire   [25:0] mul_ln270_4_fu_630_p2;
wire  signed [17:0] mul_ln270_5_fu_650_p0;
wire   [10:0] mul_ln270_5_fu_650_p1;
wire   [25:0] mul_ln270_5_fu_650_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to3;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [25:0] mul_ln270_1_fu_570_p10;
wire   [25:0] mul_ln270_2_fu_590_p10;
wire   [25:0] mul_ln270_3_fu_610_p10;
wire   [25:0] mul_ln270_4_fu_630_p10;
wire   [25:0] mul_ln270_5_fu_650_p10;
wire   [25:0] mul_ln270_fu_550_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 layer7_out_0_preg = 16'd0;
#0 layer7_out_1_preg = 16'd0;
#0 layer7_out_2_preg = 16'd0;
#0 layer7_out_3_preg = 16'd0;
#0 layer7_out_4_preg = 16'd0;
#0 layer7_out_5_preg = 16'd0;
end

myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_exp_table_ROM_Abkb #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0_local),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1_local),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2_local),
    .q2(exp_table_q2),
    .address3(exp_table_address3),
    .ce3(exp_table_ce3_local),
    .q3(exp_table_q3),
    .address4(exp_table_address4),
    .ce4(exp_table_ce4_local),
    .q4(exp_table_q4),
    .address5(exp_table_address5),
    .ce5(exp_table_ce5_local),
    .q5(exp_table_q5)
);

myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_invert_table_ROcud #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0_local),
    .q0(invert_table_q0)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U4736(
    .din0(mul_ln270_fu_550_p0),
    .din1(mul_ln270_fu_550_p1),
    .dout(mul_ln270_fu_550_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U4737(
    .din0(mul_ln270_1_fu_570_p0),
    .din1(mul_ln270_1_fu_570_p1),
    .dout(mul_ln270_1_fu_570_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U4738(
    .din0(mul_ln270_2_fu_590_p0),
    .din1(mul_ln270_2_fu_590_p1),
    .dout(mul_ln270_2_fu_590_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U4739(
    .din0(mul_ln270_3_fu_610_p0),
    .din1(mul_ln270_3_fu_610_p1),
    .dout(mul_ln270_3_fu_610_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U4740(
    .din0(mul_ln270_4_fu_630_p0),
    .din1(mul_ln270_4_fu_630_p1),
    .dout(mul_ln270_4_fu_630_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U4741(
    .din0(mul_ln270_5_fu_650_p0),
    .din1(mul_ln270_5_fu_650_p1),
    .dout(mul_ln270_5_fu_650_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer7_out_0_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            layer7_out_0_preg <= {{mul_ln270_fu_550_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer7_out_1_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            layer7_out_1_preg <= {{mul_ln270_1_fu_570_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer7_out_2_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            layer7_out_2_preg <= {{mul_ln270_2_fu_590_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer7_out_3_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            layer7_out_3_preg <= {{mul_ln270_3_fu_610_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer7_out_4_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            layer7_out_4_preg <= {{mul_ln270_4_fu_630_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer7_out_5_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            layer7_out_5_preg <= {{mul_ln270_5_fu_650_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        exp_table_load_1_reg_763 <= exp_table_q4;
        exp_table_load_2_reg_769 <= exp_table_q3;
        exp_table_load_4_reg_780 <= exp_table_q2;
        exp_table_load_5_reg_786 <= exp_table_q1;
        exp_table_load_reg_757 <= exp_table_q5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exp_table_load_1_reg_763_pp0_iter3_reg <= exp_table_load_1_reg_763;
        exp_table_load_2_reg_769_pp0_iter3_reg <= exp_table_load_2_reg_769;
        exp_table_load_4_reg_780_pp0_iter3_reg <= exp_table_load_4_reg_780;
        exp_table_load_5_reg_786_pp0_iter3_reg <= exp_table_load_5_reg_786;
        exp_table_load_reg_757_pp0_iter3_reg <= exp_table_load_reg_757;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        exp_table_load_3_reg_792 <= exp_table_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln66_2_reg_687 <= icmp_ln66_2_fu_266_p2;
        icmp_ln66_3_reg_692 <= icmp_ln66_3_fu_272_p2;
        p_read_1_reg_667 <= p_read5;
        p_read_2_reg_672 <= p_read4;
        select_ln66_1_reg_682 <= select_ln66_1_fu_258_p3;
        select_ln66_reg_677 <= select_ln66_fu_238_p3;
        tmp_6_reg_742 <= {{d_xi_xmax_3_fu_367_p2[14:5]}};
        trunc_ln248_1_reg_702 <= trunc_ln248_1_fu_282_p1;
        trunc_ln248_2_reg_707 <= trunc_ln248_2_fu_286_p1;
        trunc_ln248_3_reg_712 <= trunc_ln248_3_fu_290_p1;
        trunc_ln248_4_reg_717 <= trunc_ln248_4_fu_294_p1;
        trunc_ln248_5_reg_722 <= trunc_ln248_5_fu_298_p1;
        trunc_ln248_reg_697 <= trunc_ln248_fu_278_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        exp_table_ce0_local = 1'b1;
    end else begin
        exp_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce1_local = 1'b1;
    end else begin
        exp_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce2_local = 1'b1;
    end else begin
        exp_table_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce3_local = 1'b1;
    end else begin
        exp_table_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce4_local = 1'b1;
    end else begin
        exp_table_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce5_local = 1'b1;
    end else begin
        exp_table_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        invert_table_ce0_local = 1'b1;
    end else begin
        invert_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_0 = {{mul_ln270_fu_550_p2[25:10]}};
    end else begin
        layer7_out_0 = layer7_out_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_0_ap_vld = 1'b1;
    end else begin
        layer7_out_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_1 = {{mul_ln270_1_fu_570_p2[25:10]}};
    end else begin
        layer7_out_1 = layer7_out_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_1_ap_vld = 1'b1;
    end else begin
        layer7_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_2 = {{mul_ln270_2_fu_590_p2[25:10]}};
    end else begin
        layer7_out_2 = layer7_out_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_2_ap_vld = 1'b1;
    end else begin
        layer7_out_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_3 = {{mul_ln270_3_fu_610_p2[25:10]}};
    end else begin
        layer7_out_3 = layer7_out_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_3_ap_vld = 1'b1;
    end else begin
        layer7_out_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_4 = {{mul_ln270_4_fu_630_p2[25:10]}};
    end else begin
        layer7_out_4 = layer7_out_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_4_ap_vld = 1'b1;
    end else begin
        layer7_out_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_5 = {{mul_ln270_5_fu_650_p2[25:10]}};
    end else begin
        layer7_out_5 = layer7_out_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        layer7_out_5_ap_vld = 1'b1;
    end else begin
        layer7_out_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_1_fu_496_p2 = (add_ln51_fu_490_p2 + zext_ln145_1_fu_474_p1);

assign add_ln51_2_fu_506_p2 = (zext_ln51_1_fu_502_p1 + zext_ln145_3_fu_480_p1);

assign add_ln51_3_fu_512_p2 = (zext_ln145_4_fu_484_p1 + zext_ln51_fu_487_p1);

assign add_ln51_4_fu_522_p2 = (zext_ln51_2_fu_518_p1 + add_ln51_2_fu_506_p2);

assign add_ln51_fu_490_p2 = (zext_ln145_fu_471_p1 + zext_ln145_2_fu_477_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign d_xi_xmax_1_fu_357_p2 = (select_ln66_4_fu_344_p3 - trunc_ln248_1_reg_702);

assign d_xi_xmax_2_fu_362_p2 = (select_ln66_4_fu_344_p3 - trunc_ln248_2_reg_707);

assign d_xi_xmax_3_fu_367_p2 = (select_ln66_4_fu_344_p3 - trunc_ln248_3_reg_712);

assign d_xi_xmax_4_fu_372_p2 = (select_ln66_4_fu_344_p3 - trunc_ln248_4_reg_717);

assign d_xi_xmax_5_fu_377_p2 = (select_ln66_4_fu_344_p3 - trunc_ln248_5_reg_722);

assign d_xi_xmax_fu_352_p2 = (select_ln66_4_fu_344_p3 - trunc_ln248_reg_697);

assign exp_table_address0 = zext_ln258_3_fu_467_p1;

assign exp_table_address1 = zext_ln258_5_fu_462_p1;

assign exp_table_address2 = zext_ln258_4_fu_447_p1;

assign exp_table_address3 = zext_ln258_2_fu_422_p1;

assign exp_table_address4 = zext_ln258_1_fu_407_p1;

assign exp_table_address5 = zext_ln258_fu_392_p1;

assign icmp_ln66_1_fu_246_p2 = (($signed(p_read2) < $signed(p_read3)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_266_p2 = (($signed(select_ln66_fu_238_p3) < $signed(select_ln66_1_fu_258_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_272_p2 = (($signed(p_read4) < $signed(p_read5)) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_324_p2 = (($signed(select_ln66_2_fu_307_p3) < $signed(select_ln66_3_fu_318_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_226_p2 = (($signed(p_read) < $signed(p_read1)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln267_fu_538_p1;

assign mul_ln270_1_fu_570_p0 = sext_ln270_fu_543_p1;

assign mul_ln270_1_fu_570_p1 = mul_ln270_1_fu_570_p10;

assign mul_ln270_1_fu_570_p10 = exp_table_load_1_reg_763_pp0_iter3_reg;

assign mul_ln270_2_fu_590_p0 = sext_ln270_fu_543_p1;

assign mul_ln270_2_fu_590_p1 = mul_ln270_2_fu_590_p10;

assign mul_ln270_2_fu_590_p10 = exp_table_load_2_reg_769_pp0_iter3_reg;

assign mul_ln270_3_fu_610_p0 = sext_ln270_fu_543_p1;

assign mul_ln270_3_fu_610_p1 = mul_ln270_3_fu_610_p10;

assign mul_ln270_3_fu_610_p10 = exp_table_load_3_reg_792;

assign mul_ln270_4_fu_630_p0 = sext_ln270_fu_543_p1;

assign mul_ln270_4_fu_630_p1 = mul_ln270_4_fu_630_p10;

assign mul_ln270_4_fu_630_p10 = exp_table_load_4_reg_780_pp0_iter3_reg;

assign mul_ln270_5_fu_650_p0 = sext_ln270_fu_543_p1;

assign mul_ln270_5_fu_650_p1 = mul_ln270_5_fu_650_p10;

assign mul_ln270_5_fu_650_p10 = exp_table_load_5_reg_786_pp0_iter3_reg;

assign mul_ln270_fu_550_p0 = sext_ln270_fu_543_p1;

assign mul_ln270_fu_550_p1 = mul_ln270_fu_550_p10;

assign mul_ln270_fu_550_p10 = exp_table_load_reg_757_pp0_iter3_reg;

assign select_ln66_1_fu_258_p3 = ((xor_ln66_1_fu_252_p2[0:0] == 1'b1) ? p_read2 : p_read3);

assign select_ln66_2_fu_307_p3 = ((xor_ln66_2_fu_302_p2[0:0] == 1'b1) ? select_ln66_reg_677 : select_ln66_1_reg_682);

assign select_ln66_3_fu_318_p3 = ((xor_ln66_3_fu_313_p2[0:0] == 1'b1) ? p_read_2_reg_672 : p_read_1_reg_667);

assign select_ln66_4_fu_344_p3 = ((xor_ln66_4_fu_330_p2[0:0] == 1'b1) ? trunc_ln66_fu_336_p1 : trunc_ln66_1_fu_340_p1);

assign select_ln66_fu_238_p3 = ((xor_ln66_fu_232_p2[0:0] == 1'b1) ? p_read : p_read1);

assign sext_ln270_fu_543_p1 = $signed(invert_table_q0);

assign tmp_1_fu_528_p4 = {{add_ln51_4_fu_522_p2[12:8]}};

assign tmp_2_fu_397_p4 = {{d_xi_xmax_1_fu_357_p2[14:5]}};

assign tmp_4_fu_412_p4 = {{d_xi_xmax_2_fu_362_p2[14:5]}};

assign tmp_8_fu_437_p4 = {{d_xi_xmax_4_fu_372_p2[14:5]}};

assign tmp_fu_382_p4 = {{d_xi_xmax_fu_352_p2[14:5]}};

assign tmp_s_fu_452_p4 = {{d_xi_xmax_5_fu_377_p2[14:5]}};

assign trunc_ln248_1_fu_282_p1 = p_read1[14:0];

assign trunc_ln248_2_fu_286_p1 = p_read2[14:0];

assign trunc_ln248_3_fu_290_p1 = p_read3[14:0];

assign trunc_ln248_4_fu_294_p1 = p_read4[14:0];

assign trunc_ln248_5_fu_298_p1 = p_read5[14:0];

assign trunc_ln248_fu_278_p1 = p_read[14:0];

assign trunc_ln66_1_fu_340_p1 = select_ln66_3_fu_318_p3[14:0];

assign trunc_ln66_fu_336_p1 = select_ln66_2_fu_307_p3[14:0];

assign xor_ln66_1_fu_252_p2 = (icmp_ln66_1_fu_246_p2 ^ 1'd1);

assign xor_ln66_2_fu_302_p2 = (icmp_ln66_2_reg_687 ^ 1'd1);

assign xor_ln66_3_fu_313_p2 = (icmp_ln66_3_reg_692 ^ 1'd1);

assign xor_ln66_4_fu_330_p2 = (icmp_ln66_4_fu_324_p2 ^ 1'd1);

assign xor_ln66_fu_232_p2 = (icmp_ln66_fu_226_p2 ^ 1'd1);

assign zext_ln145_1_fu_474_p1 = exp_table_load_1_reg_763;

assign zext_ln145_2_fu_477_p1 = exp_table_load_2_reg_769;

assign zext_ln145_3_fu_480_p1 = exp_table_q0;

assign zext_ln145_4_fu_484_p1 = exp_table_load_4_reg_780;

assign zext_ln145_fu_471_p1 = exp_table_load_reg_757;

assign zext_ln258_1_fu_407_p1 = tmp_2_fu_397_p4;

assign zext_ln258_2_fu_422_p1 = tmp_4_fu_412_p4;

assign zext_ln258_3_fu_467_p1 = tmp_6_reg_742;

assign zext_ln258_4_fu_447_p1 = tmp_8_fu_437_p4;

assign zext_ln258_5_fu_462_p1 = tmp_s_fu_452_p4;

assign zext_ln258_fu_392_p1 = tmp_fu_382_p4;

assign zext_ln267_fu_538_p1 = tmp_1_fu_528_p4;

assign zext_ln51_1_fu_502_p1 = add_ln51_1_fu_496_p2;

assign zext_ln51_2_fu_518_p1 = add_ln51_3_fu_512_p2;

assign zext_ln51_fu_487_p1 = exp_table_load_5_reg_786;

endmodule //myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s
