-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer6_out_dout : IN STD_LOGIC_VECTOR (95 downto 0);
    layer6_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_empty_n : IN STD_LOGIC;
    layer6_out_read : OUT STD_LOGIC;
    layer7_out_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
    layer7_out_TVALID : OUT STD_LOGIC;
    layer7_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_5E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011110";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal exp_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q1 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q2 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q3 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q4 : STD_LOGIC_VECTOR (10 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal layer6_out_blk_n : STD_LOGIC;
    signal layer7_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal trunc_ln198_4_fu_386_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_4_reg_863 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_5_fu_396_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_5_reg_868 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_fu_418_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_reg_873 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_1_fu_438_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_1_reg_878 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_2_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_2_reg_883 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_reg_888 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln213_fu_458_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_reg_893 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_2_reg_898 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_3_reg_903 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_4_reg_908 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_5_reg_913 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln213_6_reg_918 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_5_reg_938 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_load_reg_953 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal exp_table_load_1_reg_959 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_2_reg_965 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_4_reg_976 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_5_reg_982 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_load_3_reg_988 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal inv_exp_sum_reg_998 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln223_fu_602_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_1_fu_617_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_2_fu_632_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_4_fu_657_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_5_fu_672_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_3_fu_677_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln232_fu_748_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal layer6_out_read_local : STD_LOGIC;
    signal exp_table_ce4_local : STD_LOGIC;
    signal exp_table_ce3_local : STD_LOGIC;
    signal exp_table_ce2_local : STD_LOGIC;
    signal exp_table_ce1_local : STD_LOGIC;
    signal exp_table_ce0_local : STD_LOGIC;
    signal exp_table_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_ce0_local : STD_LOGIC;
    signal mul_ln241_3_fu_201_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln241_fu_753_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_3_fu_201_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln241_2_fu_202_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_2_fu_202_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln241_5_fu_203_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_5_fu_203_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln241_fu_204_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_fu_204_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln241_1_fu_205_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_1_fu_205_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln241_4_fu_206_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_4_fu_206_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln198_fu_352_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_1_fu_356_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln198_2_fu_366_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_3_fu_376_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_1_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_2_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_3_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_2_fu_517_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_3_fu_528_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_4_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_4_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_fu_546_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln66_1_fu_550_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln66_4_fu_554_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_fu_562_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_2_fu_592_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_1_fu_567_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_3_fu_607_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_2_fu_572_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_4_fu_622_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_3_fu_577_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_4_fu_582_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_6_fu_647_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_5_fu_587_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_7_fu_662_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln145_fu_681_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln145_2_fu_687_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_fu_700_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln145_1_fu_684_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_1_fu_706_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_1_fu_712_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln145_3_fu_690_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln145_4_fu_694_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_fu_697_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_3_fu_722_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln51_2_fu_728_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln51_2_fu_716_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln51_4_fu_732_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_738_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln241_fu_204_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_1_fu_205_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_2_fu_202_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_3_fu_201_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_4_fu_206_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_5_fu_203_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln241_5_fu_836_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_4_fu_822_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_3_fu_808_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_2_fu_794_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_1_fu_780_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln2_fu_766_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal mul_ln241_1_fu_205_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_2_fu_202_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_3_fu_201_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_4_fu_206_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_5_fu_203_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_fu_204_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_18s_11ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s_exp_tablebkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s_invert_tacud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s_exp_tablebkb
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0_local,
        ce0 => exp_table_ce0_local,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1_local,
        q1 => exp_table_q1,
        address2 => exp_table_address2,
        ce2 => exp_table_ce2_local,
        q2 => exp_table_q2,
        address3 => exp_table_address3,
        ce3 => exp_table_ce3_local,
        q3 => exp_table_q3,
        address4 => exp_table_address4,
        ce4 => exp_table_ce4_local,
        q4 => exp_table_q4);

    invert_table_U : component myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s_invert_tacud
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0_local,
        q0 => invert_table_q0);

    mul_18s_11ns_26_1_1_U559 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_3_fu_201_p0,
        din1 => mul_ln241_3_fu_201_p1,
        dout => mul_ln241_3_fu_201_p2);

    mul_18s_11ns_26_1_1_U560 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_2_fu_202_p0,
        din1 => mul_ln241_2_fu_202_p1,
        dout => mul_ln241_2_fu_202_p2);

    mul_18s_11ns_26_1_1_U561 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_5_fu_203_p0,
        din1 => mul_ln241_5_fu_203_p1,
        dout => mul_ln241_5_fu_203_p2);

    mul_18s_11ns_26_1_1_U562 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_fu_204_p0,
        din1 => mul_ln241_fu_204_p1,
        dout => mul_ln241_fu_204_p2);

    mul_18s_11ns_26_1_1_U563 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_1_fu_205_p0,
        din1 => mul_ln241_1_fu_205_p1,
        dout => mul_ln241_1_fu_205_p2);

    mul_18s_11ns_26_1_1_U564 : component myproject_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_4_fu_206_p0,
        din1 => mul_ln241_4_fu_206_p1,
        dout => mul_ln241_4_fu_206_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                exp_table_load_1_reg_959 <= exp_table_q3;
                exp_table_load_2_reg_965 <= exp_table_q2;
                exp_table_load_4_reg_976 <= exp_table_q1;
                exp_table_load_5_reg_982 <= exp_table_q0;
                exp_table_load_reg_953 <= exp_table_q4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                exp_table_load_3_reg_988 <= exp_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln66_2_reg_883 <= icmp_ln66_2_fu_446_p2;
                icmp_ln66_3_reg_888 <= icmp_ln66_3_fu_452_p2;
                select_ln66_1_reg_878 <= select_ln66_1_fu_438_p3;
                select_ln66_reg_873 <= select_ln66_fu_418_p3;
                trunc_ln198_4_reg_863 <= layer6_out_dout(79 downto 64);
                trunc_ln198_5_reg_868 <= layer6_out_dout(95 downto 80);
                trunc_ln213_2_reg_898 <= layer6_out_dout(30 downto 16);
                trunc_ln213_3_reg_903 <= layer6_out_dout(46 downto 32);
                trunc_ln213_4_reg_908 <= layer6_out_dout(62 downto 48);
                trunc_ln213_5_reg_913 <= layer6_out_dout(78 downto 64);
                trunc_ln213_6_reg_918 <= layer6_out_dout(94 downto 80);
                trunc_ln213_reg_893 <= trunc_ln213_fu_458_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                inv_exp_sum_reg_998 <= invert_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_5_reg_938 <= d_xi_xmax_3_fu_577_p2(14 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer7_out_TREADY, ap_CS_fsm_state6, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((layer7_out_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln51_1_fu_706_p2 <= std_logic_vector(unsigned(add_ln51_fu_700_p2) + unsigned(zext_ln145_1_fu_684_p1));
    add_ln51_2_fu_716_p2 <= std_logic_vector(unsigned(zext_ln51_1_fu_712_p1) + unsigned(zext_ln145_3_fu_690_p1));
    add_ln51_3_fu_722_p2 <= std_logic_vector(unsigned(zext_ln145_4_fu_694_p1) + unsigned(zext_ln51_fu_697_p1));
    add_ln51_4_fu_732_p2 <= std_logic_vector(unsigned(zext_ln51_2_fu_728_p1) + unsigned(add_ln51_2_fu_716_p2));
    add_ln51_fu_700_p2 <= std_logic_vector(unsigned(zext_ln145_fu_681_p1) + unsigned(zext_ln145_2_fu_687_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(layer7_out_TREADY)
    begin
        if ((layer7_out_TREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, layer6_out_empty_n)
    begin
                ap_block_state1 <= ((layer6_out_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    d_xi_xmax_1_fu_567_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_554_p3) - unsigned(trunc_ln213_2_reg_898));
    d_xi_xmax_2_fu_572_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_554_p3) - unsigned(trunc_ln213_3_reg_903));
    d_xi_xmax_3_fu_577_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_554_p3) - unsigned(trunc_ln213_4_reg_908));
    d_xi_xmax_4_fu_582_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_554_p3) - unsigned(trunc_ln213_5_reg_913));
    d_xi_xmax_5_fu_587_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_554_p3) - unsigned(trunc_ln213_6_reg_918));
    d_xi_xmax_fu_562_p2 <= std_logic_vector(unsigned(select_ln66_4_fu_554_p3) - unsigned(trunc_ln213_reg_893));

    exp_table_address0_local_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln223_5_fu_672_p1, zext_ln223_3_fu_677_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_address0_local <= zext_ln223_3_fu_677_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            exp_table_address0_local <= zext_ln223_5_fu_672_p1(10 - 1 downto 0);
        else 
            exp_table_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;

    exp_table_address1 <= zext_ln223_4_fu_657_p1(10 - 1 downto 0);
    exp_table_address2 <= zext_ln223_2_fu_632_p1(10 - 1 downto 0);
    exp_table_address3 <= zext_ln223_1_fu_617_p1(10 - 1 downto 0);
    exp_table_address4 <= zext_ln223_fu_602_p1(10 - 1 downto 0);

    exp_table_ce0_local_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            exp_table_ce0_local <= ap_const_logic_1;
        else 
            exp_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            exp_table_ce1_local <= ap_const_logic_1;
        else 
            exp_table_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce2_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            exp_table_ce2_local <= ap_const_logic_1;
        else 
            exp_table_ce2_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce3_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            exp_table_ce3_local <= ap_const_logic_1;
        else 
            exp_table_ce3_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce4_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            exp_table_ce4_local <= ap_const_logic_1;
        else 
            exp_table_ce4_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln66_1_fu_426_p2 <= "1" when (signed(trunc_ln198_2_fu_366_p4) < signed(trunc_ln198_3_fu_376_p4)) else "0";
    icmp_ln66_2_fu_446_p2 <= "1" when (signed(select_ln66_fu_418_p3) < signed(select_ln66_1_fu_438_p3)) else "0";
    icmp_ln66_3_fu_452_p2 <= "1" when (signed(trunc_ln198_4_fu_386_p4) < signed(trunc_ln198_5_fu_396_p4)) else "0";
    icmp_ln66_4_fu_534_p2 <= "1" when (signed(select_ln66_2_fu_517_p3) < signed(select_ln66_3_fu_528_p3)) else "0";
    icmp_ln66_fu_406_p2 <= "1" when (signed(trunc_ln198_fu_352_p1) < signed(trunc_ln198_1_fu_356_p4)) else "0";
    invert_table_address0 <= zext_ln232_fu_748_p1(10 - 1 downto 0);

    invert_table_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            invert_table_ce0_local <= ap_const_logic_1;
        else 
            invert_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    layer6_out_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, layer6_out_empty_n)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            layer6_out_blk_n <= layer6_out_empty_n;
        else 
            layer6_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer6_out_read <= layer6_out_read_local;

    layer6_out_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            layer6_out_read_local <= ap_const_logic_1;
        else 
            layer6_out_read_local <= ap_const_logic_0;
        end if; 
    end process;

    layer7_out_TDATA <= (((((trunc_ln241_5_fu_836_p4 & trunc_ln241_4_fu_822_p4) & trunc_ln241_3_fu_808_p4) & trunc_ln241_2_fu_794_p4) & trunc_ln241_1_fu_780_p4) & trunc_ln2_fu_766_p4);

    layer7_out_TDATA_blk_n_assign_proc : process(layer7_out_TREADY, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            layer7_out_TDATA_blk_n <= layer7_out_TREADY;
        else 
            layer7_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer7_out_TVALID_assign_proc : process(layer7_out_TREADY, ap_CS_fsm_state6)
    begin
        if (((layer7_out_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            layer7_out_TVALID <= ap_const_logic_1;
        else 
            layer7_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln241_1_fu_205_p0 <= sext_ln241_fu_753_p1(18 - 1 downto 0);
    mul_ln241_1_fu_205_p1 <= mul_ln241_1_fu_205_p10(11 - 1 downto 0);
    mul_ln241_1_fu_205_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_1_reg_959),26));
    mul_ln241_2_fu_202_p0 <= sext_ln241_fu_753_p1(18 - 1 downto 0);
    mul_ln241_2_fu_202_p1 <= mul_ln241_2_fu_202_p10(11 - 1 downto 0);
    mul_ln241_2_fu_202_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_2_reg_965),26));
    mul_ln241_3_fu_201_p0 <= sext_ln241_fu_753_p1(18 - 1 downto 0);
    mul_ln241_3_fu_201_p1 <= mul_ln241_3_fu_201_p10(11 - 1 downto 0);
    mul_ln241_3_fu_201_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_3_reg_988),26));
    mul_ln241_4_fu_206_p0 <= sext_ln241_fu_753_p1(18 - 1 downto 0);
    mul_ln241_4_fu_206_p1 <= mul_ln241_4_fu_206_p10(11 - 1 downto 0);
    mul_ln241_4_fu_206_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_4_reg_976),26));
    mul_ln241_5_fu_203_p0 <= sext_ln241_fu_753_p1(18 - 1 downto 0);
    mul_ln241_5_fu_203_p1 <= mul_ln241_5_fu_203_p10(11 - 1 downto 0);
    mul_ln241_5_fu_203_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_5_reg_982),26));
    mul_ln241_fu_204_p0 <= sext_ln241_fu_753_p1(18 - 1 downto 0);
    mul_ln241_fu_204_p1 <= mul_ln241_fu_204_p10(11 - 1 downto 0);
    mul_ln241_fu_204_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_reg_953),26));
    select_ln66_1_fu_438_p3 <= 
        trunc_ln198_2_fu_366_p4 when (xor_ln66_1_fu_432_p2(0) = '1') else 
        trunc_ln198_3_fu_376_p4;
    select_ln66_2_fu_517_p3 <= 
        select_ln66_reg_873 when (xor_ln66_2_fu_512_p2(0) = '1') else 
        select_ln66_1_reg_878;
    select_ln66_3_fu_528_p3 <= 
        trunc_ln198_4_reg_863 when (xor_ln66_3_fu_523_p2(0) = '1') else 
        trunc_ln198_5_reg_868;
    select_ln66_4_fu_554_p3 <= 
        trunc_ln66_fu_546_p1 when (xor_ln66_4_fu_540_p2(0) = '1') else 
        trunc_ln66_1_fu_550_p1;
    select_ln66_fu_418_p3 <= 
        trunc_ln198_fu_352_p1 when (xor_ln66_fu_412_p2(0) = '1') else 
        trunc_ln198_1_fu_356_p4;
        sext_ln241_fu_753_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inv_exp_sum_reg_998),26));

    tmp_2_fu_592_p4 <= d_xi_xmax_fu_562_p2(14 downto 5);
    tmp_3_fu_607_p4 <= d_xi_xmax_1_fu_567_p2(14 downto 5);
    tmp_4_fu_622_p4 <= d_xi_xmax_2_fu_572_p2(14 downto 5);
    tmp_6_fu_647_p4 <= d_xi_xmax_4_fu_582_p2(14 downto 5);
    tmp_7_fu_662_p4 <= d_xi_xmax_5_fu_587_p2(14 downto 5);
    tmp_fu_738_p4 <= add_ln51_4_fu_732_p2(12 downto 8);
    trunc_ln198_1_fu_356_p4 <= layer6_out_dout(31 downto 16);
    trunc_ln198_2_fu_366_p4 <= layer6_out_dout(47 downto 32);
    trunc_ln198_3_fu_376_p4 <= layer6_out_dout(63 downto 48);
    trunc_ln198_4_fu_386_p4 <= layer6_out_dout(79 downto 64);
    trunc_ln198_5_fu_396_p4 <= layer6_out_dout(95 downto 80);
    trunc_ln198_fu_352_p1 <= layer6_out_dout(16 - 1 downto 0);
    trunc_ln213_fu_458_p1 <= layer6_out_dout(15 - 1 downto 0);
    trunc_ln241_1_fu_780_p4 <= mul_ln241_1_fu_205_p2(25 downto 10);
    trunc_ln241_2_fu_794_p4 <= mul_ln241_2_fu_202_p2(25 downto 10);
    trunc_ln241_3_fu_808_p4 <= mul_ln241_3_fu_201_p2(25 downto 10);
    trunc_ln241_4_fu_822_p4 <= mul_ln241_4_fu_206_p2(25 downto 10);
    trunc_ln241_5_fu_836_p4 <= mul_ln241_5_fu_203_p2(25 downto 10);
    trunc_ln2_fu_766_p4 <= mul_ln241_fu_204_p2(25 downto 10);
    trunc_ln66_1_fu_550_p1 <= select_ln66_3_fu_528_p3(15 - 1 downto 0);
    trunc_ln66_fu_546_p1 <= select_ln66_2_fu_517_p3(15 - 1 downto 0);
    xor_ln66_1_fu_432_p2 <= (icmp_ln66_1_fu_426_p2 xor ap_const_lv1_1);
    xor_ln66_2_fu_512_p2 <= (icmp_ln66_2_reg_883 xor ap_const_lv1_1);
    xor_ln66_3_fu_523_p2 <= (icmp_ln66_3_reg_888 xor ap_const_lv1_1);
    xor_ln66_4_fu_540_p2 <= (icmp_ln66_4_fu_534_p2 xor ap_const_lv1_1);
    xor_ln66_fu_412_p2 <= (icmp_ln66_fu_406_p2 xor ap_const_lv1_1);
    zext_ln145_1_fu_684_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_1_reg_959),12));
    zext_ln145_2_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_2_reg_965),12));
    zext_ln145_3_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q0),13));
    zext_ln145_4_fu_694_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_4_reg_976),12));
    zext_ln145_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_reg_953),12));
    zext_ln223_1_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_607_p4),64));
    zext_ln223_2_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_622_p4),64));
    zext_ln223_3_fu_677_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_reg_938),64));
    zext_ln223_4_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_647_p4),64));
    zext_ln223_5_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_662_p4),64));
    zext_ln223_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_592_p4),64));
    zext_ln232_fu_748_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_738_p4),64));
    zext_ln51_1_fu_712_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln51_1_fu_706_p2),13));
    zext_ln51_2_fu_728_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln51_3_fu_722_p2),13));
    zext_ln51_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_5_reg_982),12));
end behav;
