-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_6u_config6_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer5_out_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer5_out_empty_n : IN STD_LOGIC;
    layer5_out_read : OUT STD_LOGIC;
    layer6_out_din : OUT STD_LOGIC_VECTOR (95 downto 0);
    layer6_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_full_n : IN STD_LOGIC;
    layer6_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_6u_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer5_out_blk_n : STD_LOGIC;
    signal layer6_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_pack_fu_117_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_reg_312 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_pack_16_reg_317 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_17_reg_322 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_18_reg_327 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_19_reg_332 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_20_reg_337 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_21_reg_342 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_22_reg_347 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_23_reg_352 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_24_reg_357 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_25_reg_362 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_26_reg_367 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_27_reg_372 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_28_reg_377 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_29_reg_382 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_pack_30_reg_387 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_done : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_idle : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_ready : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal layer5_out_read_local : STD_LOGIC;
    signal p_s_fu_295_p7 : STD_LOGIC_VECTOR (95 downto 0);
    signal layer6_out_write_local : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_val1 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_val2 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_val3 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_val4 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_val5 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_val6 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_val7 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_val8 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_8_val9 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_9_val10 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_10_val11 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_11_val12 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_12_val13 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_13_val14 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_14_val15 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_15_val16 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97 : component myproject_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start,
        ap_done => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_done,
        ap_idle => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_idle,
        ap_ready => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_ready,
        data_0_val1 => data_pack_reg_312,
        data_1_val2 => data_pack_16_reg_317,
        data_2_val3 => data_pack_17_reg_322,
        data_3_val4 => data_pack_18_reg_327,
        data_4_val5 => data_pack_19_reg_332,
        data_5_val6 => data_pack_20_reg_337,
        data_6_val7 => data_pack_21_reg_342,
        data_7_val8 => data_pack_22_reg_347,
        data_8_val9 => data_pack_23_reg_352,
        data_9_val10 => data_pack_24_reg_357,
        data_10_val11 => data_pack_25_reg_362,
        data_11_val12 => data_pack_26_reg_367,
        data_12_val13 => data_pack_27_reg_372,
        data_13_val14 => data_pack_28_reg_377,
        data_14_val15 => data_pack_29_reg_382,
        data_15_val16 => data_pack_30_reg_387,
        ap_return_0 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_0,
        ap_return_1 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_1,
        ap_return_2 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_2,
        ap_return_3 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_3,
        ap_return_4 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_4,
        ap_return_5 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_NS_fsm_state2))) then 
                    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_ready = ap_const_logic_1)) then 
                    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_pack_16_reg_317 <= layer5_out_dout(31 downto 16);
                data_pack_17_reg_322 <= layer5_out_dout(47 downto 32);
                data_pack_18_reg_327 <= layer5_out_dout(63 downto 48);
                data_pack_19_reg_332 <= layer5_out_dout(79 downto 64);
                data_pack_20_reg_337 <= layer5_out_dout(95 downto 80);
                data_pack_21_reg_342 <= layer5_out_dout(111 downto 96);
                data_pack_22_reg_347 <= layer5_out_dout(127 downto 112);
                data_pack_23_reg_352 <= layer5_out_dout(143 downto 128);
                data_pack_24_reg_357 <= layer5_out_dout(159 downto 144);
                data_pack_25_reg_362 <= layer5_out_dout(175 downto 160);
                data_pack_26_reg_367 <= layer5_out_dout(191 downto 176);
                data_pack_27_reg_372 <= layer5_out_dout(207 downto 192);
                data_pack_28_reg_377 <= layer5_out_dout(223 downto 208);
                data_pack_29_reg_382 <= layer5_out_dout(239 downto 224);
                data_pack_30_reg_387 <= layer5_out_dout(255 downto 240);
                data_pack_reg_312 <= data_pack_fu_117_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer6_out_full_n, ap_CS_fsm_state3, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer6_out_full_n)
    begin
        if ((layer6_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer5_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer5_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer6_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_pack_fu_117_p1 <= layer5_out_dout(16 - 1 downto 0);
    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg;

    internal_ap_ready_assign_proc : process(layer6_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer5_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer5_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer5_out_blk_n <= layer5_out_empty_n;
        else 
            layer5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer5_out_read <= layer5_out_read_local;

    layer5_out_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer5_out_read_local <= ap_const_logic_1;
        else 
            layer5_out_read_local <= ap_const_logic_0;
        end if; 
    end process;


    layer6_out_blk_n_assign_proc : process(layer6_out_full_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer6_out_blk_n <= layer6_out_full_n;
        else 
            layer6_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer6_out_din <= p_s_fu_295_p7;
    layer6_out_write <= layer6_out_write_local;

    layer6_out_write_local_assign_proc : process(layer6_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer6_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer6_out_write_local <= ap_const_logic_1;
        else 
            layer6_out_write_local <= ap_const_logic_0;
        end if; 
    end process;

    p_s_fu_295_p7 <= (((((grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_5 & grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_4) & grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_3) & grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_2) & grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_1) & grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
