-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_global_pooling1d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer4_out_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    layer4_out_empty_n : IN STD_LOGIC;
    layer4_out_read : OUT STD_LOGIC;
    layer5_out_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer5_out_full_n : IN STD_LOGIC;
    layer5_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_global_pooling1d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer5_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_idle : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_ready : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_layer4_out_read : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out_ap_vld : STD_LOGIC;
    signal grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call19 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal data_window_loc_fu_84 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_1_loc_fu_80 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_2_loc_fu_76 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_3_loc_fu_72 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_4_loc_fu_68 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_5_loc_fu_64 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_6_loc_fu_60 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_7_loc_fu_56 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_8_loc_fu_52 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_9_loc_fu_48 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_10_loc_fu_44 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_11_loc_fu_40 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_12_loc_fu_36 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_13_loc_fu_32 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_14_loc_fu_28 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_window_15_loc_fu_24 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_fu_165_p17 : STD_LOGIC_VECTOR (255 downto 0);
    signal layer5_out_write_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer4_out_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        layer4_out_empty_n : IN STD_LOGIC;
        layer4_out_read : OUT STD_LOGIC;
        data_window_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_out_ap_vld : OUT STD_LOGIC;
        data_window_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_1_out_ap_vld : OUT STD_LOGIC;
        data_window_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_2_out_ap_vld : OUT STD_LOGIC;
        data_window_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_3_out_ap_vld : OUT STD_LOGIC;
        data_window_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_4_out_ap_vld : OUT STD_LOGIC;
        data_window_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_5_out_ap_vld : OUT STD_LOGIC;
        data_window_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_6_out_ap_vld : OUT STD_LOGIC;
        data_window_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_7_out_ap_vld : OUT STD_LOGIC;
        data_window_8_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_8_out_ap_vld : OUT STD_LOGIC;
        data_window_9_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_9_out_ap_vld : OUT STD_LOGIC;
        data_window_10_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_10_out_ap_vld : OUT STD_LOGIC;
        data_window_11_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_11_out_ap_vld : OUT STD_LOGIC;
        data_window_12_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_12_out_ap_vld : OUT STD_LOGIC;
        data_window_13_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_13_out_ap_vld : OUT STD_LOGIC;
        data_window_14_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_14_out_ap_vld : OUT STD_LOGIC;
        data_window_15_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        data_window_15_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95 : component myproject_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start,
        ap_done => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done,
        ap_idle => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_idle,
        ap_ready => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_ready,
        layer4_out_dout => layer4_out_dout,
        layer4_out_num_data_valid => ap_const_lv8_0,
        layer4_out_fifo_cap => ap_const_lv8_0,
        layer4_out_empty_n => layer4_out_empty_n,
        layer4_out_read => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_layer4_out_read,
        data_window_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out,
        data_window_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out_ap_vld,
        data_window_1_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out,
        data_window_1_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out_ap_vld,
        data_window_2_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out,
        data_window_2_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out_ap_vld,
        data_window_3_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out,
        data_window_3_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out_ap_vld,
        data_window_4_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out,
        data_window_4_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out_ap_vld,
        data_window_5_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out,
        data_window_5_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out_ap_vld,
        data_window_6_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out,
        data_window_6_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out_ap_vld,
        data_window_7_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out,
        data_window_7_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out_ap_vld,
        data_window_8_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out,
        data_window_8_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out_ap_vld,
        data_window_9_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out,
        data_window_9_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out_ap_vld,
        data_window_10_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out,
        data_window_10_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out_ap_vld,
        data_window_11_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out,
        data_window_11_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out_ap_vld,
        data_window_12_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out,
        data_window_12_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out_ap_vld,
        data_window_13_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out,
        data_window_13_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out_ap_vld,
        data_window_14_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out,
        data_window_14_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out_ap_vld,
        data_window_15_out => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out,
        data_window_15_out_ap_vld => grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_ignore_call19))) then 
                    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_ready = ap_const_logic_1)) then 
                    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_10_loc_fu_44 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_11_loc_fu_40 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_12_loc_fu_36 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_13_loc_fu_32 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_14_loc_fu_28 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_15_loc_fu_24 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_1_loc_fu_80 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_2_loc_fu_76 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_3_loc_fu_72 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_4_loc_fu_68 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_5_loc_fu_64 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_6_loc_fu_60 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_7_loc_fu_56 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_8_loc_fu_52 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_9_loc_fu_48 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                data_window_loc_fu_84 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer5_out_full_n, ap_CS_fsm_state3, grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done, ap_CS_fsm_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done)
    begin
        if ((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(layer5_out_full_n)
    begin
        if ((layer5_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call19_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call19 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer5_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg;

    internal_ap_ready_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer4_out_read_assign_proc : process(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_layer4_out_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer4_out_read <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_layer4_out_read;
        else 
            layer4_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer5_out_blk_n_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer5_out_blk_n <= layer5_out_full_n;
        else 
            layer5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer5_out_din <= p_0_fu_165_p17;
    layer5_out_write <= layer5_out_write_local;

    layer5_out_write_local_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer5_out_write_local <= ap_const_logic_1;
        else 
            layer5_out_write_local <= ap_const_logic_0;
        end if; 
    end process;

    p_0_fu_165_p17 <= (((((((((((((((data_window_15_loc_fu_24 & data_window_14_loc_fu_28) & data_window_13_loc_fu_32) & data_window_12_loc_fu_36) & data_window_11_loc_fu_40) & data_window_10_loc_fu_44) & data_window_9_loc_fu_48) & data_window_8_loc_fu_52) & data_window_7_loc_fu_56) & data_window_6_loc_fu_60) & data_window_5_loc_fu_64) & data_window_4_loc_fu_68) & data_window_3_loc_fu_72) & data_window_2_loc_fu_76) & data_window_1_loc_fu_80) & data_window_loc_fu_84);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
