-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer4_out_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    layer4_out_empty_n : IN STD_LOGIC;
    layer4_out_read : OUT STD_LOGIC;
    data_window_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_out_ap_vld : OUT STD_LOGIC;
    data_window_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_1_out_ap_vld : OUT STD_LOGIC;
    data_window_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_2_out_ap_vld : OUT STD_LOGIC;
    data_window_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_3_out_ap_vld : OUT STD_LOGIC;
    data_window_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_4_out_ap_vld : OUT STD_LOGIC;
    data_window_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_5_out_ap_vld : OUT STD_LOGIC;
    data_window_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_6_out_ap_vld : OUT STD_LOGIC;
    data_window_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_7_out_ap_vld : OUT STD_LOGIC;
    data_window_8_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_8_out_ap_vld : OUT STD_LOGIC;
    data_window_9_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_9_out_ap_vld : OUT STD_LOGIC;
    data_window_10_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_10_out_ap_vld : OUT STD_LOGIC;
    data_window_11_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_11_out_ap_vld : OUT STD_LOGIC;
    data_window_12_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_12_out_ap_vld : OUT STD_LOGIC;
    data_window_13_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_13_out_ap_vld : OUT STD_LOGIC;
    data_window_14_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_14_out_ap_vld : OUT STD_LOGIC;
    data_window_15_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    data_window_15_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of myproject_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln306_fu_852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal x_assign_152_fu_130 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_15_fu_837_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal x_assign_144_fu_134 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_14_fu_822_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_136_fu_138 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_13_fu_807_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_128_fu_142 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_12_fu_792_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_1110_fu_146 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_11_fu_777_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_1012_fu_150 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_10_fu_762_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_914_fu_154 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_9_fu_747_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_816_fu_158 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_8_fu_732_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_718_fu_162 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_7_fu_717_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_620_fu_166 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_6_fu_702_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_522_fu_170 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_5_fu_687_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_424_fu_174 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_4_fu_672_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_326_fu_178 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_3_fu_657_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_228_fu_182 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_2_fu_642_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign_130_fu_186 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_1_fu_627_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_assign32_fu_190 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal data_window_fu_612_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_iw33_fu_194 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal i_iw_fu_846_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal layer4_out_read_local : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal y_max_fu_452_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_1_fu_456_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_1_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_2_fu_466_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_2_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_3_fu_476_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_3_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_4_fu_486_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_4_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_5_fu_496_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_5_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_6_fu_506_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_6_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_7_fu_516_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_7_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_8_fu_526_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_8_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_9_fu_536_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_9_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_15_fu_546_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_10_fu_756_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_10_fu_556_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_11_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_11_fu_566_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_12_fu_786_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_12_fu_576_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_13_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_13_fu_586_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_14_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_max_14_fu_596_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_15_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component myproject_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_iw33_fu_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_iw33_fu_194 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_iw33_fu_194 <= i_iw_fu_846_p2;
                end if;
            end if; 
        end if;
    end process;

    x_assign32_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign32_fu_190 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign32_fu_190 <= data_window_fu_612_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_1012_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_1012_fu_150 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_1012_fu_150 <= data_window_10_fu_762_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_1110_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_1110_fu_146 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_1110_fu_146 <= data_window_11_fu_777_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_128_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_128_fu_142 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_128_fu_142 <= data_window_12_fu_792_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_130_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_130_fu_186 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_130_fu_186 <= data_window_1_fu_627_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_136_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_136_fu_138 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_136_fu_138 <= data_window_13_fu_807_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_144_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_144_fu_134 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_144_fu_134 <= data_window_14_fu_822_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_152_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_152_fu_130 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_152_fu_130 <= data_window_15_fu_837_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_228_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_228_fu_182 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_228_fu_182 <= data_window_2_fu_642_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_326_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_326_fu_178 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_326_fu_178 <= data_window_3_fu_657_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_424_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_424_fu_174 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_424_fu_174 <= data_window_4_fu_672_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_522_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_522_fu_170 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_522_fu_170 <= data_window_5_fu_687_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_620_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_620_fu_166 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_620_fu_166 <= data_window_6_fu_702_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_718_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_718_fu_162 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_718_fu_162 <= data_window_7_fu_717_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_816_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_816_fu_158 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_816_fu_158 <= data_window_8_fu_732_p3;
                end if;
            end if; 
        end if;
    end process;

    x_assign_914_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_assign_914_fu_154 <= ap_const_lv16_8000;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_assign_914_fu_154 <= data_window_9_fu_747_p3;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer4_out_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer4_out_empty_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln306_fu_852_p2)
    begin
        if (((icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    data_window_10_fu_762_p3 <= 
        x_assign_1012_fu_150 when (icmp_ln200_10_fu_756_p2(0) = '1') else 
        y_max_15_fu_546_p4;
    data_window_10_out <= 
        x_assign_1012_fu_150 when (icmp_ln200_10_fu_756_p2(0) = '1') else 
        y_max_15_fu_546_p4;

    data_window_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_10_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_11_fu_777_p3 <= 
        x_assign_1110_fu_146 when (icmp_ln200_11_fu_771_p2(0) = '1') else 
        y_max_10_fu_556_p4;
    data_window_11_out <= 
        x_assign_1110_fu_146 when (icmp_ln200_11_fu_771_p2(0) = '1') else 
        y_max_10_fu_556_p4;

    data_window_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_11_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_12_fu_792_p3 <= 
        x_assign_128_fu_142 when (icmp_ln200_12_fu_786_p2(0) = '1') else 
        y_max_11_fu_566_p4;
    data_window_12_out <= 
        x_assign_128_fu_142 when (icmp_ln200_12_fu_786_p2(0) = '1') else 
        y_max_11_fu_566_p4;

    data_window_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_12_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_13_fu_807_p3 <= 
        x_assign_136_fu_138 when (icmp_ln200_13_fu_801_p2(0) = '1') else 
        y_max_12_fu_576_p4;
    data_window_13_out <= 
        x_assign_136_fu_138 when (icmp_ln200_13_fu_801_p2(0) = '1') else 
        y_max_12_fu_576_p4;

    data_window_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_13_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_14_fu_822_p3 <= 
        x_assign_144_fu_134 when (icmp_ln200_14_fu_816_p2(0) = '1') else 
        y_max_13_fu_586_p4;
    data_window_14_out <= 
        x_assign_144_fu_134 when (icmp_ln200_14_fu_816_p2(0) = '1') else 
        y_max_13_fu_586_p4;

    data_window_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_14_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_15_fu_837_p3 <= 
        x_assign_152_fu_130 when (icmp_ln200_15_fu_831_p2(0) = '1') else 
        y_max_14_fu_596_p4;
    data_window_15_out <= 
        x_assign_152_fu_130 when (icmp_ln200_15_fu_831_p2(0) = '1') else 
        y_max_14_fu_596_p4;

    data_window_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_15_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_1_fu_627_p3 <= 
        x_assign_130_fu_186 when (icmp_ln200_1_fu_621_p2(0) = '1') else 
        y_max_1_fu_456_p4;
    data_window_1_out <= 
        x_assign_130_fu_186 when (icmp_ln200_1_fu_621_p2(0) = '1') else 
        y_max_1_fu_456_p4;

    data_window_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_1_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_2_fu_642_p3 <= 
        x_assign_228_fu_182 when (icmp_ln200_2_fu_636_p2(0) = '1') else 
        y_max_2_fu_466_p4;
    data_window_2_out <= 
        x_assign_228_fu_182 when (icmp_ln200_2_fu_636_p2(0) = '1') else 
        y_max_2_fu_466_p4;

    data_window_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_2_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_3_fu_657_p3 <= 
        x_assign_326_fu_178 when (icmp_ln200_3_fu_651_p2(0) = '1') else 
        y_max_3_fu_476_p4;
    data_window_3_out <= 
        x_assign_326_fu_178 when (icmp_ln200_3_fu_651_p2(0) = '1') else 
        y_max_3_fu_476_p4;

    data_window_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_3_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_4_fu_672_p3 <= 
        x_assign_424_fu_174 when (icmp_ln200_4_fu_666_p2(0) = '1') else 
        y_max_4_fu_486_p4;
    data_window_4_out <= 
        x_assign_424_fu_174 when (icmp_ln200_4_fu_666_p2(0) = '1') else 
        y_max_4_fu_486_p4;

    data_window_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_4_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_5_fu_687_p3 <= 
        x_assign_522_fu_170 when (icmp_ln200_5_fu_681_p2(0) = '1') else 
        y_max_5_fu_496_p4;
    data_window_5_out <= 
        x_assign_522_fu_170 when (icmp_ln200_5_fu_681_p2(0) = '1') else 
        y_max_5_fu_496_p4;

    data_window_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_5_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_6_fu_702_p3 <= 
        x_assign_620_fu_166 when (icmp_ln200_6_fu_696_p2(0) = '1') else 
        y_max_6_fu_506_p4;
    data_window_6_out <= 
        x_assign_620_fu_166 when (icmp_ln200_6_fu_696_p2(0) = '1') else 
        y_max_6_fu_506_p4;

    data_window_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_6_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_7_fu_717_p3 <= 
        x_assign_718_fu_162 when (icmp_ln200_7_fu_711_p2(0) = '1') else 
        y_max_7_fu_516_p4;
    data_window_7_out <= 
        x_assign_718_fu_162 when (icmp_ln200_7_fu_711_p2(0) = '1') else 
        y_max_7_fu_516_p4;

    data_window_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_7_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_8_fu_732_p3 <= 
        x_assign_816_fu_158 when (icmp_ln200_8_fu_726_p2(0) = '1') else 
        y_max_8_fu_526_p4;
    data_window_8_out <= 
        x_assign_816_fu_158 when (icmp_ln200_8_fu_726_p2(0) = '1') else 
        y_max_8_fu_526_p4;

    data_window_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_8_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_9_fu_747_p3 <= 
        x_assign_914_fu_154 when (icmp_ln200_9_fu_741_p2(0) = '1') else 
        y_max_9_fu_536_p4;
    data_window_9_out <= 
        x_assign_914_fu_154 when (icmp_ln200_9_fu_741_p2(0) = '1') else 
        y_max_9_fu_536_p4;

    data_window_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_9_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_window_fu_612_p3 <= 
        x_assign32_fu_190 when (icmp_ln200_fu_606_p2(0) = '1') else 
        y_max_fu_452_p1;
    data_window_out <= 
        x_assign32_fu_190 when (icmp_ln200_fu_606_p2(0) = '1') else 
        y_max_fu_452_p1;

    data_window_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln306_fu_852_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln306_fu_852_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_window_out_ap_vld <= ap_const_logic_1;
        else 
            data_window_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    i_iw_fu_846_p2 <= std_logic_vector(unsigned(i_iw33_fu_194) + unsigned(ap_const_lv7_1));
    icmp_ln200_10_fu_756_p2 <= "1" when (signed(y_max_15_fu_546_p4) < signed(x_assign_1012_fu_150)) else "0";
    icmp_ln200_11_fu_771_p2 <= "1" when (signed(y_max_10_fu_556_p4) < signed(x_assign_1110_fu_146)) else "0";
    icmp_ln200_12_fu_786_p2 <= "1" when (signed(y_max_11_fu_566_p4) < signed(x_assign_128_fu_142)) else "0";
    icmp_ln200_13_fu_801_p2 <= "1" when (signed(y_max_12_fu_576_p4) < signed(x_assign_136_fu_138)) else "0";
    icmp_ln200_14_fu_816_p2 <= "1" when (signed(y_max_13_fu_586_p4) < signed(x_assign_144_fu_134)) else "0";
    icmp_ln200_15_fu_831_p2 <= "1" when (signed(y_max_14_fu_596_p4) < signed(x_assign_152_fu_130)) else "0";
    icmp_ln200_1_fu_621_p2 <= "1" when (signed(y_max_1_fu_456_p4) < signed(x_assign_130_fu_186)) else "0";
    icmp_ln200_2_fu_636_p2 <= "1" when (signed(y_max_2_fu_466_p4) < signed(x_assign_228_fu_182)) else "0";
    icmp_ln200_3_fu_651_p2 <= "1" when (signed(y_max_3_fu_476_p4) < signed(x_assign_326_fu_178)) else "0";
    icmp_ln200_4_fu_666_p2 <= "1" when (signed(y_max_4_fu_486_p4) < signed(x_assign_424_fu_174)) else "0";
    icmp_ln200_5_fu_681_p2 <= "1" when (signed(y_max_5_fu_496_p4) < signed(x_assign_522_fu_170)) else "0";
    icmp_ln200_6_fu_696_p2 <= "1" when (signed(y_max_6_fu_506_p4) < signed(x_assign_620_fu_166)) else "0";
    icmp_ln200_7_fu_711_p2 <= "1" when (signed(y_max_7_fu_516_p4) < signed(x_assign_718_fu_162)) else "0";
    icmp_ln200_8_fu_726_p2 <= "1" when (signed(y_max_8_fu_526_p4) < signed(x_assign_816_fu_158)) else "0";
    icmp_ln200_9_fu_741_p2 <= "1" when (signed(y_max_9_fu_536_p4) < signed(x_assign_914_fu_154)) else "0";
    icmp_ln200_fu_606_p2 <= "1" when (signed(y_max_fu_452_p1) < signed(x_assign32_fu_190)) else "0";
    icmp_ln306_fu_852_p2 <= "1" when (i_iw33_fu_194 = ap_const_lv7_7F) else "0";

    layer4_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer4_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer4_out_blk_n <= layer4_out_empty_n;
        else 
            layer4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer4_out_read <= layer4_out_read_local;

    layer4_out_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer4_out_read_local <= ap_const_logic_1;
        else 
            layer4_out_read_local <= ap_const_logic_0;
        end if; 
    end process;

    y_max_10_fu_556_p4 <= layer4_out_dout(191 downto 176);
    y_max_11_fu_566_p4 <= layer4_out_dout(207 downto 192);
    y_max_12_fu_576_p4 <= layer4_out_dout(223 downto 208);
    y_max_13_fu_586_p4 <= layer4_out_dout(239 downto 224);
    y_max_14_fu_596_p4 <= layer4_out_dout(255 downto 240);
    y_max_15_fu_546_p4 <= layer4_out_dout(175 downto 160);
    y_max_1_fu_456_p4 <= layer4_out_dout(31 downto 16);
    y_max_2_fu_466_p4 <= layer4_out_dout(47 downto 32);
    y_max_3_fu_476_p4 <= layer4_out_dout(63 downto 48);
    y_max_4_fu_486_p4 <= layer4_out_dout(79 downto 64);
    y_max_5_fu_496_p4 <= layer4_out_dout(95 downto 80);
    y_max_6_fu_506_p4 <= layer4_out_dout(111 downto 96);
    y_max_7_fu_516_p4 <= layer4_out_dout(127 downto 112);
    y_max_8_fu_526_p4 <= layer4_out_dout(143 downto 128);
    y_max_9_fu_536_p4 <= layer4_out_dout(159 downto 144);
    y_max_fu_452_p1 <= layer4_out_dout(16 - 1 downto 0);
end behav;
