// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_relu_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer2_out_dout,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_empty_n,
        layer2_out_read,
        layer4_out_din,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_full_n,
        layer4_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] layer2_out_dout;
input  [7:0] layer2_out_num_data_valid;
input  [7:0] layer2_out_fifo_cap;
input   layer2_out_empty_n;
output   layer2_out_read;
output  [255:0] layer4_out_din;
input  [7:0] layer4_out_num_data_valid;
input  [7:0] layer4_out_fifo_cap;
input   layer4_out_full_n;
output   layer4_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln41_fu_800_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer2_out_blk_n;
reg    layer4_out_blk_n;
reg   [6:0] i1_fu_136;
wire   [6:0] i_fu_794_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i1_load;
reg    layer2_out_read_local;
wire   [255:0] zext_ln57_fu_789_p1;
reg    layer4_out_write_local;
wire   [15:0] in_data_fu_161_p1;
wire   [0:0] icmp_ln51_fu_469_p2;
wire   [14:0] trunc_ln44_28_fu_165_p1;
wire   [14:0] out_data_1_fu_475_p3;
wire   [15:0] in_data_4_fu_169_p4;
wire   [0:0] icmp_ln51_1_fu_487_p2;
wire   [14:0] trunc_ln44_1_fu_179_p4;
wire   [14:0] out_data_3_fu_493_p3;
wire   [15:0] in_data_5_fu_189_p4;
wire   [0:0] icmp_ln51_2_fu_505_p2;
wire   [14:0] trunc_ln44_2_fu_199_p4;
wire   [14:0] out_data_5_fu_511_p3;
wire   [15:0] in_data_6_fu_209_p4;
wire   [0:0] icmp_ln51_3_fu_523_p2;
wire   [14:0] trunc_ln44_3_fu_219_p4;
wire   [14:0] out_data_7_fu_529_p3;
wire   [15:0] trunc_ln44_4_fu_229_p4;
wire   [0:0] icmp_ln51_4_fu_541_p2;
wire   [14:0] trunc_ln44_s_fu_239_p4;
wire   [14:0] select_ln51_fu_547_p3;
wire   [15:0] trunc_ln44_5_fu_249_p4;
wire   [0:0] icmp_ln51_5_fu_559_p2;
wire   [14:0] trunc_ln44_16_fu_259_p4;
wire   [14:0] select_ln51_1_fu_565_p3;
wire   [15:0] trunc_ln44_6_fu_269_p4;
wire   [0:0] icmp_ln51_6_fu_577_p2;
wire   [14:0] trunc_ln44_17_fu_279_p4;
wire   [14:0] select_ln51_2_fu_583_p3;
wire   [15:0] trunc_ln44_7_fu_289_p4;
wire   [0:0] icmp_ln51_7_fu_595_p2;
wire   [14:0] trunc_ln44_18_fu_299_p4;
wire   [14:0] select_ln51_3_fu_601_p3;
wire   [15:0] trunc_ln44_8_fu_309_p4;
wire   [0:0] icmp_ln51_8_fu_613_p2;
wire   [14:0] trunc_ln44_19_fu_319_p4;
wire   [14:0] select_ln51_4_fu_619_p3;
wire   [15:0] trunc_ln44_9_fu_329_p4;
wire   [0:0] icmp_ln51_9_fu_631_p2;
wire   [14:0] trunc_ln44_20_fu_339_p4;
wire   [14:0] select_ln51_5_fu_637_p3;
wire   [15:0] trunc_ln44_10_fu_349_p4;
wire   [0:0] icmp_ln51_10_fu_649_p2;
wire   [14:0] trunc_ln44_21_fu_359_p4;
wire   [14:0] select_ln51_6_fu_655_p3;
wire   [15:0] trunc_ln44_11_fu_369_p4;
wire   [0:0] icmp_ln51_11_fu_667_p2;
wire   [14:0] trunc_ln44_22_fu_379_p4;
wire   [14:0] select_ln51_7_fu_673_p3;
wire   [15:0] trunc_ln44_12_fu_389_p4;
wire   [0:0] icmp_ln51_12_fu_685_p2;
wire   [14:0] trunc_ln44_23_fu_399_p4;
wire   [14:0] select_ln51_8_fu_691_p3;
wire   [15:0] trunc_ln44_13_fu_409_p4;
wire   [0:0] icmp_ln51_13_fu_703_p2;
wire   [14:0] trunc_ln44_24_fu_419_p4;
wire   [14:0] select_ln51_9_fu_709_p3;
wire   [15:0] trunc_ln44_14_fu_429_p4;
wire   [0:0] icmp_ln51_14_fu_721_p2;
wire   [14:0] trunc_ln44_25_fu_439_p4;
wire   [14:0] select_ln51_10_fu_727_p3;
wire   [15:0] trunc_ln44_15_fu_449_p4;
wire   [0:0] icmp_ln51_15_fu_739_p2;
wire   [14:0] trunc_ln44_26_fu_459_p4;
wire   [14:0] select_ln51_11_fu_745_p3;
wire   [15:0] zext_ln51_11_fu_735_p1;
wire   [15:0] zext_ln51_10_fu_717_p1;
wire   [15:0] zext_ln51_9_fu_699_p1;
wire   [15:0] zext_ln51_8_fu_681_p1;
wire   [15:0] zext_ln51_7_fu_663_p1;
wire   [15:0] zext_ln51_6_fu_645_p1;
wire   [15:0] zext_ln51_5_fu_627_p1;
wire   [15:0] zext_ln51_4_fu_609_p1;
wire   [15:0] zext_ln51_3_fu_591_p1;
wire   [15:0] zext_ln51_2_fu_573_p1;
wire   [15:0] zext_ln51_fu_555_p1;
wire   [15:0] zext_ln45_3_fu_537_p1;
wire   [15:0] zext_ln45_2_fu_519_p1;
wire   [15:0] zext_ln45_1_fu_501_p1;
wire   [15:0] zext_ln45_fu_483_p1;
wire   [254:0] or_ln57_s_fu_753_p17;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 i1_fu_136 = 7'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i1_fu_136 <= i_fu_794_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_800_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i1_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_136;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_blk_n = layer2_out_empty_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_read_local = 1'b1;
    end else begin
        layer2_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_write_local = 1'b1;
    end else begin
        layer4_out_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (ap_done_reg == 1'b1) | (layer4_out_full_n == 1'b0) | (layer2_out_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_fu_794_p2 = (ap_sig_allocacmp_i1_load + 7'd1);

assign icmp_ln41_fu_800_p2 = ((ap_sig_allocacmp_i1_load == 7'd127) ? 1'b1 : 1'b0);

assign icmp_ln51_10_fu_649_p2 = (($signed(trunc_ln44_10_fu_349_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_667_p2 = (($signed(trunc_ln44_11_fu_369_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_685_p2 = (($signed(trunc_ln44_12_fu_389_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_703_p2 = (($signed(trunc_ln44_13_fu_409_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_721_p2 = (($signed(trunc_ln44_14_fu_429_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_739_p2 = (($signed(trunc_ln44_15_fu_449_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_487_p2 = (($signed(in_data_4_fu_169_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_505_p2 = (($signed(in_data_5_fu_189_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_523_p2 = (($signed(in_data_6_fu_209_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_541_p2 = (($signed(trunc_ln44_4_fu_229_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_559_p2 = (($signed(trunc_ln44_5_fu_249_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_577_p2 = (($signed(trunc_ln44_6_fu_269_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_595_p2 = (($signed(trunc_ln44_7_fu_289_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_613_p2 = (($signed(trunc_ln44_8_fu_309_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_631_p2 = (($signed(trunc_ln44_9_fu_329_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_469_p2 = (($signed(in_data_fu_161_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign in_data_4_fu_169_p4 = {{layer2_out_dout[31:16]}};

assign in_data_5_fu_189_p4 = {{layer2_out_dout[47:32]}};

assign in_data_6_fu_209_p4 = {{layer2_out_dout[63:48]}};

assign in_data_fu_161_p1 = layer2_out_dout[15:0];

assign layer2_out_read = layer2_out_read_local;

assign layer4_out_din = zext_ln57_fu_789_p1;

assign layer4_out_write = layer4_out_write_local;

assign or_ln57_s_fu_753_p17 = {{{{{{{{{{{{{{{{select_ln51_11_fu_745_p3}, {zext_ln51_11_fu_735_p1}}, {zext_ln51_10_fu_717_p1}}, {zext_ln51_9_fu_699_p1}}, {zext_ln51_8_fu_681_p1}}, {zext_ln51_7_fu_663_p1}}, {zext_ln51_6_fu_645_p1}}, {zext_ln51_5_fu_627_p1}}, {zext_ln51_4_fu_609_p1}}, {zext_ln51_3_fu_591_p1}}, {zext_ln51_2_fu_573_p1}}, {zext_ln51_fu_555_p1}}, {zext_ln45_3_fu_537_p1}}, {zext_ln45_2_fu_519_p1}}, {zext_ln45_1_fu_501_p1}}, {zext_ln45_fu_483_p1}};

assign out_data_1_fu_475_p3 = ((icmp_ln51_fu_469_p2[0:0] == 1'b1) ? trunc_ln44_28_fu_165_p1 : 15'd0);

assign out_data_3_fu_493_p3 = ((icmp_ln51_1_fu_487_p2[0:0] == 1'b1) ? trunc_ln44_1_fu_179_p4 : 15'd0);

assign out_data_5_fu_511_p3 = ((icmp_ln51_2_fu_505_p2[0:0] == 1'b1) ? trunc_ln44_2_fu_199_p4 : 15'd0);

assign out_data_7_fu_529_p3 = ((icmp_ln51_3_fu_523_p2[0:0] == 1'b1) ? trunc_ln44_3_fu_219_p4 : 15'd0);

assign select_ln51_10_fu_727_p3 = ((icmp_ln51_14_fu_721_p2[0:0] == 1'b1) ? trunc_ln44_25_fu_439_p4 : 15'd0);

assign select_ln51_11_fu_745_p3 = ((icmp_ln51_15_fu_739_p2[0:0] == 1'b1) ? trunc_ln44_26_fu_459_p4 : 15'd0);

assign select_ln51_1_fu_565_p3 = ((icmp_ln51_5_fu_559_p2[0:0] == 1'b1) ? trunc_ln44_16_fu_259_p4 : 15'd0);

assign select_ln51_2_fu_583_p3 = ((icmp_ln51_6_fu_577_p2[0:0] == 1'b1) ? trunc_ln44_17_fu_279_p4 : 15'd0);

assign select_ln51_3_fu_601_p3 = ((icmp_ln51_7_fu_595_p2[0:0] == 1'b1) ? trunc_ln44_18_fu_299_p4 : 15'd0);

assign select_ln51_4_fu_619_p3 = ((icmp_ln51_8_fu_613_p2[0:0] == 1'b1) ? trunc_ln44_19_fu_319_p4 : 15'd0);

assign select_ln51_5_fu_637_p3 = ((icmp_ln51_9_fu_631_p2[0:0] == 1'b1) ? trunc_ln44_20_fu_339_p4 : 15'd0);

assign select_ln51_6_fu_655_p3 = ((icmp_ln51_10_fu_649_p2[0:0] == 1'b1) ? trunc_ln44_21_fu_359_p4 : 15'd0);

assign select_ln51_7_fu_673_p3 = ((icmp_ln51_11_fu_667_p2[0:0] == 1'b1) ? trunc_ln44_22_fu_379_p4 : 15'd0);

assign select_ln51_8_fu_691_p3 = ((icmp_ln51_12_fu_685_p2[0:0] == 1'b1) ? trunc_ln44_23_fu_399_p4 : 15'd0);

assign select_ln51_9_fu_709_p3 = ((icmp_ln51_13_fu_703_p2[0:0] == 1'b1) ? trunc_ln44_24_fu_419_p4 : 15'd0);

assign select_ln51_fu_547_p3 = ((icmp_ln51_4_fu_541_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_239_p4 : 15'd0);

assign start_out = real_start;

assign trunc_ln44_10_fu_349_p4 = {{layer2_out_dout[175:160]}};

assign trunc_ln44_11_fu_369_p4 = {{layer2_out_dout[191:176]}};

assign trunc_ln44_12_fu_389_p4 = {{layer2_out_dout[207:192]}};

assign trunc_ln44_13_fu_409_p4 = {{layer2_out_dout[223:208]}};

assign trunc_ln44_14_fu_429_p4 = {{layer2_out_dout[239:224]}};

assign trunc_ln44_15_fu_449_p4 = {{layer2_out_dout[255:240]}};

assign trunc_ln44_16_fu_259_p4 = {{layer2_out_dout[94:80]}};

assign trunc_ln44_17_fu_279_p4 = {{layer2_out_dout[110:96]}};

assign trunc_ln44_18_fu_299_p4 = {{layer2_out_dout[126:112]}};

assign trunc_ln44_19_fu_319_p4 = {{layer2_out_dout[142:128]}};

assign trunc_ln44_1_fu_179_p4 = {{layer2_out_dout[30:16]}};

assign trunc_ln44_20_fu_339_p4 = {{layer2_out_dout[158:144]}};

assign trunc_ln44_21_fu_359_p4 = {{layer2_out_dout[174:160]}};

assign trunc_ln44_22_fu_379_p4 = {{layer2_out_dout[190:176]}};

assign trunc_ln44_23_fu_399_p4 = {{layer2_out_dout[206:192]}};

assign trunc_ln44_24_fu_419_p4 = {{layer2_out_dout[222:208]}};

assign trunc_ln44_25_fu_439_p4 = {{layer2_out_dout[238:224]}};

assign trunc_ln44_26_fu_459_p4 = {{layer2_out_dout[254:240]}};

assign trunc_ln44_28_fu_165_p1 = layer2_out_dout[14:0];

assign trunc_ln44_2_fu_199_p4 = {{layer2_out_dout[46:32]}};

assign trunc_ln44_3_fu_219_p4 = {{layer2_out_dout[62:48]}};

assign trunc_ln44_4_fu_229_p4 = {{layer2_out_dout[79:64]}};

assign trunc_ln44_5_fu_249_p4 = {{layer2_out_dout[95:80]}};

assign trunc_ln44_6_fu_269_p4 = {{layer2_out_dout[111:96]}};

assign trunc_ln44_7_fu_289_p4 = {{layer2_out_dout[127:112]}};

assign trunc_ln44_8_fu_309_p4 = {{layer2_out_dout[143:128]}};

assign trunc_ln44_9_fu_329_p4 = {{layer2_out_dout[159:144]}};

assign trunc_ln44_s_fu_239_p4 = {{layer2_out_dout[78:64]}};

assign zext_ln45_1_fu_501_p1 = out_data_3_fu_493_p3;

assign zext_ln45_2_fu_519_p1 = out_data_5_fu_511_p3;

assign zext_ln45_3_fu_537_p1 = out_data_7_fu_529_p3;

assign zext_ln45_fu_483_p1 = out_data_1_fu_475_p3;

assign zext_ln51_10_fu_717_p1 = select_ln51_9_fu_709_p3;

assign zext_ln51_11_fu_735_p1 = select_ln51_10_fu_727_p3;

assign zext_ln51_2_fu_573_p1 = select_ln51_1_fu_565_p3;

assign zext_ln51_3_fu_591_p1 = select_ln51_2_fu_583_p3;

assign zext_ln51_4_fu_609_p1 = select_ln51_3_fu_601_p3;

assign zext_ln51_5_fu_627_p1 = select_ln51_4_fu_619_p3;

assign zext_ln51_6_fu_645_p1 = select_ln51_5_fu_637_p3;

assign zext_ln51_7_fu_663_p1 = select_ln51_6_fu_655_p3;

assign zext_ln51_8_fu_681_p1 = select_ln51_7_fu_673_p3;

assign zext_ln51_9_fu_699_p1 = select_ln51_8_fu_691_p3;

assign zext_ln51_fu_555_p1 = select_ln51_fu_547_p3;

assign zext_ln57_fu_789_p1 = or_ln57_s_fu_753_p17;

endmodule //myproject_relu_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_relu_config4_s
