// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_6u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer5_out_dout,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_empty_n,
        layer5_out_read,
        layer6_out_din,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_full_n,
        layer6_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [255:0] layer5_out_dout;
input  [1:0] layer5_out_num_data_valid;
input  [1:0] layer5_out_fifo_cap;
input   layer5_out_empty_n;
output   layer5_out_read;
output  [95:0] layer6_out_din;
input  [1:0] layer6_out_num_data_valid;
input  [1:0] layer6_out_fifo_cap;
input   layer6_out_full_n;
output   layer6_out_write;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer5_out_blk_n;
reg    layer6_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [15:0] data_pack_fu_117_p1;
reg   [15:0] data_pack_reg_312;
reg    ap_block_state1;
reg   [15:0] data_pack_16_reg_317;
reg   [15:0] data_pack_17_reg_322;
reg   [15:0] data_pack_18_reg_327;
reg   [15:0] data_pack_19_reg_332;
reg   [15:0] data_pack_20_reg_337;
reg   [15:0] data_pack_21_reg_342;
reg   [15:0] data_pack_22_reg_347;
reg   [15:0] data_pack_23_reg_352;
reg   [15:0] data_pack_24_reg_357;
reg   [15:0] data_pack_25_reg_362;
reg   [15:0] data_pack_26_reg_367;
reg   [15:0] data_pack_27_reg_372;
reg   [15:0] data_pack_28_reg_377;
reg   [15:0] data_pack_29_reg_382;
reg   [15:0] data_pack_30_reg_387;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_done;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_idle;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_ready;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_0;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_1;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_2;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_3;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_4;
wire   [15:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_5;
reg    grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state2;
reg    layer5_out_read_local;
wire   [95:0] p_s_fu_295_p7;
reg    layer6_out_write_local;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg = 1'b0;
end

myproject_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start),
    .ap_done(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_done),
    .ap_idle(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_idle),
    .ap_ready(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_ready),
    .data_0_val1(data_pack_reg_312),
    .data_1_val2(data_pack_16_reg_317),
    .data_2_val3(data_pack_17_reg_322),
    .data_3_val4(data_pack_18_reg_327),
    .data_4_val5(data_pack_19_reg_332),
    .data_5_val6(data_pack_20_reg_337),
    .data_6_val7(data_pack_21_reg_342),
    .data_7_val8(data_pack_22_reg_347),
    .data_8_val9(data_pack_23_reg_352),
    .data_9_val10(data_pack_24_reg_357),
    .data_10_val11(data_pack_25_reg_362),
    .data_11_val12(data_pack_26_reg_367),
    .data_12_val13(data_pack_27_reg_372),
    .data_13_val14(data_pack_28_reg_377),
    .data_14_val15(data_pack_29_reg_382),
    .data_15_val16(data_pack_30_reg_387),
    .ap_return_0(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_0),
    .ap_return_1(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_1),
    .ap_return_2(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_2),
    .ap_return_3(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_3),
    .ap_return_4(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_4),
    .ap_return_5(grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_ready == 1'b1)) begin
            grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_pack_16_reg_317 <= {{layer5_out_dout[31:16]}};
        data_pack_17_reg_322 <= {{layer5_out_dout[47:32]}};
        data_pack_18_reg_327 <= {{layer5_out_dout[63:48]}};
        data_pack_19_reg_332 <= {{layer5_out_dout[79:64]}};
        data_pack_20_reg_337 <= {{layer5_out_dout[95:80]}};
        data_pack_21_reg_342 <= {{layer5_out_dout[111:96]}};
        data_pack_22_reg_347 <= {{layer5_out_dout[127:112]}};
        data_pack_23_reg_352 <= {{layer5_out_dout[143:128]}};
        data_pack_24_reg_357 <= {{layer5_out_dout[159:144]}};
        data_pack_25_reg_362 <= {{layer5_out_dout[175:160]}};
        data_pack_26_reg_367 <= {{layer5_out_dout[191:176]}};
        data_pack_27_reg_372 <= {{layer5_out_dout[207:192]}};
        data_pack_28_reg_377 <= {{layer5_out_dout[223:208]}};
        data_pack_29_reg_382 <= {{layer5_out_dout[239:224]}};
        data_pack_30_reg_387 <= {{layer5_out_dout[255:240]}};
        data_pack_reg_312 <= data_pack_fu_117_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((layer6_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer5_out_read_local = 1'b1;
    end else begin
        layer5_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer6_out_blk_n = layer6_out_full_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer6_out_write_local = 1'b1;
    end else begin
        layer6_out_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((layer6_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer5_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign data_pack_fu_117_p1 = layer5_out_dout[15:0];

assign grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start = grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_start_reg;

assign layer5_out_read = layer5_out_read_local;

assign layer6_out_din = p_s_fu_295_p7;

assign layer6_out_write = layer6_out_write_local;

assign p_s_fu_295_p7 = {{{{{{grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_5}, {grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_4}}, {grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_3}}, {grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_2}}, {grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_1}}, {grp_dense_latency_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config6_s_fu_97_ap_return_0}};

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_6u_config6_s
