// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_global_pooling1d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer4_out_dout,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_empty_n,
        layer4_out_read,
        layer5_out_din,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_full_n,
        layer5_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [255:0] layer4_out_dout;
input  [7:0] layer4_out_num_data_valid;
input  [7:0] layer4_out_fifo_cap;
input   layer4_out_empty_n;
output   layer4_out_read;
output  [255:0] layer5_out_din;
input  [1:0] layer5_out_num_data_valid;
input  [1:0] layer5_out_fifo_cap;
input   layer5_out_full_n;
output   layer5_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer4_out_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer5_out_blk_n;
wire    ap_CS_fsm_state3;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_idle;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_ready;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_layer4_out_read;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out_ap_vld;
wire   [15:0] grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out;
wire    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out_ap_vld;
reg    grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg;
reg    ap_block_state1_ignore_call19;
wire    ap_CS_fsm_state2;
reg   [15:0] data_window_loc_fu_84;
reg   [15:0] data_window_1_loc_fu_80;
reg   [15:0] data_window_2_loc_fu_76;
reg   [15:0] data_window_3_loc_fu_72;
reg   [15:0] data_window_4_loc_fu_68;
reg   [15:0] data_window_5_loc_fu_64;
reg   [15:0] data_window_6_loc_fu_60;
reg   [15:0] data_window_7_loc_fu_56;
reg   [15:0] data_window_8_loc_fu_52;
reg   [15:0] data_window_9_loc_fu_48;
reg   [15:0] data_window_10_loc_fu_44;
reg   [15:0] data_window_11_loc_fu_40;
reg   [15:0] data_window_12_loc_fu_36;
reg   [15:0] data_window_13_loc_fu_32;
reg   [15:0] data_window_14_loc_fu_28;
reg   [15:0] data_window_15_loc_fu_24;
wire   [255:0] p_0_fu_165_p17;
reg    layer5_out_write_local;
reg   [2:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg = 1'b0;
end

myproject_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start),
    .ap_done(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done),
    .ap_idle(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_idle),
    .ap_ready(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(8'd0),
    .layer4_out_fifo_cap(8'd0),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_layer4_out_read),
    .data_window_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out),
    .data_window_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out_ap_vld),
    .data_window_1_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out),
    .data_window_1_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out_ap_vld),
    .data_window_2_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out),
    .data_window_2_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out_ap_vld),
    .data_window_3_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out),
    .data_window_3_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out_ap_vld),
    .data_window_4_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out),
    .data_window_4_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out_ap_vld),
    .data_window_5_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out),
    .data_window_5_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out_ap_vld),
    .data_window_6_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out),
    .data_window_6_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out_ap_vld),
    .data_window_7_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out),
    .data_window_7_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out_ap_vld),
    .data_window_8_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out),
    .data_window_8_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out_ap_vld),
    .data_window_9_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out),
    .data_window_9_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out_ap_vld),
    .data_window_10_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out),
    .data_window_10_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out_ap_vld),
    .data_window_11_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out),
    .data_window_11_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out_ap_vld),
    .data_window_12_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out),
    .data_window_12_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out_ap_vld),
    .data_window_13_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out),
    .data_window_13_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out_ap_vld),
    .data_window_14_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out),
    .data_window_14_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out_ap_vld),
    .data_window_15_out(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out),
    .data_window_15_out_ap_vld(grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call19))) begin
            grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg <= 1'b1;
        end else if ((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_ready == 1'b1)) begin
            grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_10_loc_fu_44 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_10_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_11_loc_fu_40 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_11_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_12_loc_fu_36 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_12_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_13_loc_fu_32 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_13_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_14_loc_fu_28 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_14_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_15_loc_fu_24 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_15_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_1_loc_fu_80 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_2_loc_fu_76 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_3_loc_fu_72 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_4_loc_fu_68 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_5_loc_fu_64 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_6_loc_fu_60 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_7_loc_fu_56 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_7_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_8_loc_fu_52 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_9_loc_fu_48 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_9_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_window_loc_fu_84 <= grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_data_window_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer5_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer4_out_read = grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_layer4_out_read;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer5_out_write_local = 1'b1;
    end else begin
        layer5_out_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((layer5_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call19 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start = grp_global_pooling1d_cl_array_array_ap_fixed_16u_config5_Pipeline_ReadInput_fu_95_ap_start_reg;

assign layer5_out_din = p_0_fu_165_p17;

assign layer5_out_write = layer5_out_write_local;

assign p_0_fu_165_p17 = {{{{{{{{{{{{{{{{data_window_15_loc_fu_24}, {data_window_14_loc_fu_28}}, {data_window_13_loc_fu_32}}, {data_window_12_loc_fu_36}}, {data_window_11_loc_fu_40}}, {data_window_10_loc_fu_44}}, {data_window_9_loc_fu_48}}, {data_window_8_loc_fu_52}}, {data_window_7_loc_fu_56}}, {data_window_6_loc_fu_60}}, {data_window_5_loc_fu_64}}, {data_window_4_loc_fu_68}}, {data_window_3_loc_fu_72}}, {data_window_2_loc_fu_76}}, {data_window_1_loc_fu_80}}, {data_window_loc_fu_84}};

assign start_out = real_start;

endmodule //myproject_global_pooling1d_cl_array_array_ap_fixed_16_6_5_3_0_16u_config5_s
