// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer6_out_dout,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_empty_n,
        layer6_out_read,
        layer7_out_TDATA,
        layer7_out_TVALID,
        layer7_out_TREADY
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [95:0] layer6_out_dout;
input  [1:0] layer6_out_num_data_valid;
input  [1:0] layer6_out_fifo_cap;
input   layer6_out_empty_n;
output   layer6_out_read;
output  [95:0] layer7_out_TDATA;
output   layer7_out_TVALID;
input   layer7_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer7_out_TVALID;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [10:0] exp_table_q0;
wire   [9:0] exp_table_address1;
wire   [10:0] exp_table_q1;
wire   [9:0] exp_table_address2;
wire   [10:0] exp_table_q2;
wire   [9:0] exp_table_address3;
wire   [10:0] exp_table_q3;
wire   [9:0] exp_table_address4;
wire   [10:0] exp_table_q4;
wire   [9:0] invert_table_address0;
wire   [17:0] invert_table_q0;
reg    layer6_out_blk_n;
reg    layer7_out_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire   [15:0] trunc_ln198_4_fu_386_p4;
reg   [15:0] trunc_ln198_4_reg_863;
wire   [15:0] trunc_ln198_5_fu_396_p4;
reg   [15:0] trunc_ln198_5_reg_868;
wire   [15:0] select_ln66_fu_418_p3;
reg   [15:0] select_ln66_reg_873;
wire   [15:0] select_ln66_1_fu_438_p3;
reg   [15:0] select_ln66_1_reg_878;
wire   [0:0] icmp_ln66_2_fu_446_p2;
reg   [0:0] icmp_ln66_2_reg_883;
wire   [0:0] icmp_ln66_3_fu_452_p2;
reg   [0:0] icmp_ln66_3_reg_888;
wire   [14:0] trunc_ln213_fu_458_p1;
reg   [14:0] trunc_ln213_reg_893;
reg   [14:0] trunc_ln213_2_reg_898;
reg   [14:0] trunc_ln213_3_reg_903;
reg   [14:0] trunc_ln213_4_reg_908;
reg   [14:0] trunc_ln213_5_reg_913;
reg   [14:0] trunc_ln213_6_reg_918;
wire    ap_CS_fsm_state2;
reg   [9:0] tmp_5_reg_938;
reg   [10:0] exp_table_load_reg_953;
wire    ap_CS_fsm_state3;
reg   [10:0] exp_table_load_1_reg_959;
reg   [10:0] exp_table_load_2_reg_965;
reg   [10:0] exp_table_load_4_reg_976;
reg   [10:0] exp_table_load_5_reg_982;
reg   [10:0] exp_table_load_3_reg_988;
wire    ap_CS_fsm_state4;
reg   [17:0] inv_exp_sum_reg_998;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln223_fu_602_p1;
wire   [63:0] zext_ln223_1_fu_617_p1;
wire   [63:0] zext_ln223_2_fu_632_p1;
wire   [63:0] zext_ln223_4_fu_657_p1;
wire   [63:0] zext_ln223_5_fu_672_p1;
wire   [63:0] zext_ln223_3_fu_677_p1;
wire   [63:0] zext_ln232_fu_748_p1;
reg    ap_block_state1;
reg    layer6_out_read_local;
reg    exp_table_ce4_local;
reg    exp_table_ce3_local;
reg    exp_table_ce2_local;
reg    exp_table_ce1_local;
reg    exp_table_ce0_local;
reg   [9:0] exp_table_address0_local;
reg    invert_table_ce0_local;
wire  signed [17:0] mul_ln241_3_fu_201_p0;
wire  signed [25:0] sext_ln241_fu_753_p1;
wire   [10:0] mul_ln241_3_fu_201_p1;
wire  signed [17:0] mul_ln241_2_fu_202_p0;
wire   [10:0] mul_ln241_2_fu_202_p1;
wire  signed [17:0] mul_ln241_5_fu_203_p0;
wire   [10:0] mul_ln241_5_fu_203_p1;
wire  signed [17:0] mul_ln241_fu_204_p0;
wire   [10:0] mul_ln241_fu_204_p1;
wire  signed [17:0] mul_ln241_1_fu_205_p0;
wire   [10:0] mul_ln241_1_fu_205_p1;
wire  signed [17:0] mul_ln241_4_fu_206_p0;
wire   [10:0] mul_ln241_4_fu_206_p1;
wire   [15:0] trunc_ln198_fu_352_p1;
wire   [15:0] trunc_ln198_1_fu_356_p4;
wire   [0:0] icmp_ln66_fu_406_p2;
wire   [0:0] xor_ln66_fu_412_p2;
wire   [15:0] trunc_ln198_2_fu_366_p4;
wire   [15:0] trunc_ln198_3_fu_376_p4;
wire   [0:0] icmp_ln66_1_fu_426_p2;
wire   [0:0] xor_ln66_1_fu_432_p2;
wire   [0:0] xor_ln66_2_fu_512_p2;
wire   [0:0] xor_ln66_3_fu_523_p2;
wire   [15:0] select_ln66_2_fu_517_p3;
wire   [15:0] select_ln66_3_fu_528_p3;
wire   [0:0] icmp_ln66_4_fu_534_p2;
wire   [0:0] xor_ln66_4_fu_540_p2;
wire   [14:0] trunc_ln66_fu_546_p1;
wire   [14:0] trunc_ln66_1_fu_550_p1;
wire   [14:0] select_ln66_4_fu_554_p3;
wire   [14:0] d_xi_xmax_fu_562_p2;
wire   [9:0] tmp_2_fu_592_p4;
wire   [14:0] d_xi_xmax_1_fu_567_p2;
wire   [9:0] tmp_3_fu_607_p4;
wire   [14:0] d_xi_xmax_2_fu_572_p2;
wire   [9:0] tmp_4_fu_622_p4;
wire   [14:0] d_xi_xmax_3_fu_577_p2;
wire   [14:0] d_xi_xmax_4_fu_582_p2;
wire   [9:0] tmp_6_fu_647_p4;
wire   [14:0] d_xi_xmax_5_fu_587_p2;
wire   [9:0] tmp_7_fu_662_p4;
wire   [11:0] zext_ln145_fu_681_p1;
wire   [11:0] zext_ln145_2_fu_687_p1;
wire   [11:0] add_ln51_fu_700_p2;
wire   [11:0] zext_ln145_1_fu_684_p1;
wire   [11:0] add_ln51_1_fu_706_p2;
wire   [12:0] zext_ln51_1_fu_712_p1;
wire   [12:0] zext_ln145_3_fu_690_p1;
wire   [11:0] zext_ln145_4_fu_694_p1;
wire   [11:0] zext_ln51_fu_697_p1;
wire   [11:0] add_ln51_3_fu_722_p2;
wire   [12:0] zext_ln51_2_fu_728_p1;
wire   [12:0] add_ln51_2_fu_716_p2;
wire   [12:0] add_ln51_4_fu_732_p2;
wire   [4:0] tmp_fu_738_p4;
wire   [25:0] mul_ln241_fu_204_p2;
wire   [25:0] mul_ln241_1_fu_205_p2;
wire   [25:0] mul_ln241_2_fu_202_p2;
wire   [25:0] mul_ln241_3_fu_201_p2;
wire   [25:0] mul_ln241_4_fu_206_p2;
wire   [25:0] mul_ln241_5_fu_203_p2;
wire   [15:0] trunc_ln241_5_fu_836_p4;
wire   [15:0] trunc_ln241_4_fu_822_p4;
wire   [15:0] trunc_ln241_3_fu_808_p4;
wire   [15:0] trunc_ln241_2_fu_794_p4;
wire   [15:0] trunc_ln241_1_fu_780_p4;
wire   [15:0] trunc_ln2_fu_766_p4;
wire    ap_CS_fsm_state7;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire   [25:0] mul_ln241_1_fu_205_p10;
wire   [25:0] mul_ln241_2_fu_202_p10;
wire   [25:0] mul_ln241_3_fu_201_p10;
wire   [25:0] mul_ln241_4_fu_206_p10;
wire   [25:0] mul_ln241_5_fu_203_p10;
wire   [25:0] mul_ln241_fu_204_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
end

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s_exp_tablebkb #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0_local),
    .ce0(exp_table_ce0_local),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1_local),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2_local),
    .q2(exp_table_q2),
    .address3(exp_table_address3),
    .ce3(exp_table_ce3_local),
    .q3(exp_table_q3),
    .address4(exp_table_address4),
    .ce4(exp_table_ce4_local),
    .q4(exp_table_q4)
);

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s_invert_tacud #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0_local),
    .q0(invert_table_q0)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U559(
    .din0(mul_ln241_3_fu_201_p0),
    .din1(mul_ln241_3_fu_201_p1),
    .dout(mul_ln241_3_fu_201_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U560(
    .din0(mul_ln241_2_fu_202_p0),
    .din1(mul_ln241_2_fu_202_p1),
    .dout(mul_ln241_2_fu_202_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U561(
    .din0(mul_ln241_5_fu_203_p0),
    .din1(mul_ln241_5_fu_203_p1),
    .dout(mul_ln241_5_fu_203_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U562(
    .din0(mul_ln241_fu_204_p0),
    .din1(mul_ln241_fu_204_p1),
    .dout(mul_ln241_fu_204_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U563(
    .din0(mul_ln241_1_fu_205_p0),
    .din1(mul_ln241_1_fu_205_p1),
    .dout(mul_ln241_1_fu_205_p2)
);

myproject_mul_18s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_18s_11ns_26_1_1_U564(
    .din0(mul_ln241_4_fu_206_p0),
    .din1(mul_ln241_4_fu_206_p1),
    .dout(mul_ln241_4_fu_206_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_load_1_reg_959 <= exp_table_q3;
        exp_table_load_2_reg_965 <= exp_table_q2;
        exp_table_load_4_reg_976 <= exp_table_q1;
        exp_table_load_5_reg_982 <= exp_table_q0;
        exp_table_load_reg_953 <= exp_table_q4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        exp_table_load_3_reg_988 <= exp_table_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln66_2_reg_883 <= icmp_ln66_2_fu_446_p2;
        icmp_ln66_3_reg_888 <= icmp_ln66_3_fu_452_p2;
        select_ln66_1_reg_878 <= select_ln66_1_fu_438_p3;
        select_ln66_reg_873 <= select_ln66_fu_418_p3;
        trunc_ln198_4_reg_863 <= {{layer6_out_dout[79:64]}};
        trunc_ln198_5_reg_868 <= {{layer6_out_dout[95:80]}};
        trunc_ln213_2_reg_898 <= {{layer6_out_dout[30:16]}};
        trunc_ln213_3_reg_903 <= {{layer6_out_dout[46:32]}};
        trunc_ln213_4_reg_908 <= {{layer6_out_dout[62:48]}};
        trunc_ln213_5_reg_913 <= {{layer6_out_dout[78:64]}};
        trunc_ln213_6_reg_918 <= {{layer6_out_dout[94:80]}};
        trunc_ln213_reg_893 <= trunc_ln213_fu_458_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        inv_exp_sum_reg_998 <= invert_table_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_5_reg_938 <= {{d_xi_xmax_3_fu_577_p2[14:5]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((layer7_out_TREADY == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_address0_local = zext_ln223_3_fu_677_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_address0_local = zext_ln223_5_fu_672_p1;
    end else begin
        exp_table_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        exp_table_ce0_local = 1'b1;
    end else begin
        exp_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce1_local = 1'b1;
    end else begin
        exp_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce2_local = 1'b1;
    end else begin
        exp_table_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce3_local = 1'b1;
    end else begin
        exp_table_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce4_local = 1'b1;
    end else begin
        exp_table_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        invert_table_ce0_local = 1'b1;
    end else begin
        invert_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        layer6_out_read_local = 1'b1;
    end else begin
        layer6_out_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        layer7_out_TDATA_blk_n = layer7_out_TREADY;
    end else begin
        layer7_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer7_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        layer7_out_TVALID = 1'b1;
    end else begin
        layer7_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((layer7_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_1_fu_706_p2 = (add_ln51_fu_700_p2 + zext_ln145_1_fu_684_p1);

assign add_ln51_2_fu_716_p2 = (zext_ln51_1_fu_712_p1 + zext_ln145_3_fu_690_p1);

assign add_ln51_3_fu_722_p2 = (zext_ln145_4_fu_694_p1 + zext_ln51_fu_697_p1);

assign add_ln51_4_fu_732_p2 = (zext_ln51_2_fu_728_p1 + add_ln51_2_fu_716_p2);

assign add_ln51_fu_700_p2 = (zext_ln145_fu_681_p1 + zext_ln145_2_fu_687_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((layer6_out_empty_n == 1'b0) | (ap_start == 1'b0));
end

assign d_xi_xmax_1_fu_567_p2 = (select_ln66_4_fu_554_p3 - trunc_ln213_2_reg_898);

assign d_xi_xmax_2_fu_572_p2 = (select_ln66_4_fu_554_p3 - trunc_ln213_3_reg_903);

assign d_xi_xmax_3_fu_577_p2 = (select_ln66_4_fu_554_p3 - trunc_ln213_4_reg_908);

assign d_xi_xmax_4_fu_582_p2 = (select_ln66_4_fu_554_p3 - trunc_ln213_5_reg_913);

assign d_xi_xmax_5_fu_587_p2 = (select_ln66_4_fu_554_p3 - trunc_ln213_6_reg_918);

assign d_xi_xmax_fu_562_p2 = (select_ln66_4_fu_554_p3 - trunc_ln213_reg_893);

assign exp_table_address1 = zext_ln223_4_fu_657_p1;

assign exp_table_address2 = zext_ln223_2_fu_632_p1;

assign exp_table_address3 = zext_ln223_1_fu_617_p1;

assign exp_table_address4 = zext_ln223_fu_602_p1;

assign icmp_ln66_1_fu_426_p2 = (($signed(trunc_ln198_2_fu_366_p4) < $signed(trunc_ln198_3_fu_376_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_446_p2 = (($signed(select_ln66_fu_418_p3) < $signed(select_ln66_1_fu_438_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_452_p2 = (($signed(trunc_ln198_4_fu_386_p4) < $signed(trunc_ln198_5_fu_396_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_534_p2 = (($signed(select_ln66_2_fu_517_p3) < $signed(select_ln66_3_fu_528_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_406_p2 = (($signed(trunc_ln198_fu_352_p1) < $signed(trunc_ln198_1_fu_356_p4)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln232_fu_748_p1;

assign layer6_out_read = layer6_out_read_local;

assign layer7_out_TDATA = {{{{{{trunc_ln241_5_fu_836_p4}, {trunc_ln241_4_fu_822_p4}}, {trunc_ln241_3_fu_808_p4}}, {trunc_ln241_2_fu_794_p4}}, {trunc_ln241_1_fu_780_p4}}, {trunc_ln2_fu_766_p4}};

assign mul_ln241_1_fu_205_p0 = sext_ln241_fu_753_p1;

assign mul_ln241_1_fu_205_p1 = mul_ln241_1_fu_205_p10;

assign mul_ln241_1_fu_205_p10 = exp_table_load_1_reg_959;

assign mul_ln241_2_fu_202_p0 = sext_ln241_fu_753_p1;

assign mul_ln241_2_fu_202_p1 = mul_ln241_2_fu_202_p10;

assign mul_ln241_2_fu_202_p10 = exp_table_load_2_reg_965;

assign mul_ln241_3_fu_201_p0 = sext_ln241_fu_753_p1;

assign mul_ln241_3_fu_201_p1 = mul_ln241_3_fu_201_p10;

assign mul_ln241_3_fu_201_p10 = exp_table_load_3_reg_988;

assign mul_ln241_4_fu_206_p0 = sext_ln241_fu_753_p1;

assign mul_ln241_4_fu_206_p1 = mul_ln241_4_fu_206_p10;

assign mul_ln241_4_fu_206_p10 = exp_table_load_4_reg_976;

assign mul_ln241_5_fu_203_p0 = sext_ln241_fu_753_p1;

assign mul_ln241_5_fu_203_p1 = mul_ln241_5_fu_203_p10;

assign mul_ln241_5_fu_203_p10 = exp_table_load_5_reg_982;

assign mul_ln241_fu_204_p0 = sext_ln241_fu_753_p1;

assign mul_ln241_fu_204_p1 = mul_ln241_fu_204_p10;

assign mul_ln241_fu_204_p10 = exp_table_load_reg_953;

assign select_ln66_1_fu_438_p3 = ((xor_ln66_1_fu_432_p2[0:0] == 1'b1) ? trunc_ln198_2_fu_366_p4 : trunc_ln198_3_fu_376_p4);

assign select_ln66_2_fu_517_p3 = ((xor_ln66_2_fu_512_p2[0:0] == 1'b1) ? select_ln66_reg_873 : select_ln66_1_reg_878);

assign select_ln66_3_fu_528_p3 = ((xor_ln66_3_fu_523_p2[0:0] == 1'b1) ? trunc_ln198_4_reg_863 : trunc_ln198_5_reg_868);

assign select_ln66_4_fu_554_p3 = ((xor_ln66_4_fu_540_p2[0:0] == 1'b1) ? trunc_ln66_fu_546_p1 : trunc_ln66_1_fu_550_p1);

assign select_ln66_fu_418_p3 = ((xor_ln66_fu_412_p2[0:0] == 1'b1) ? trunc_ln198_fu_352_p1 : trunc_ln198_1_fu_356_p4);

assign sext_ln241_fu_753_p1 = $signed(inv_exp_sum_reg_998);

assign tmp_2_fu_592_p4 = {{d_xi_xmax_fu_562_p2[14:5]}};

assign tmp_3_fu_607_p4 = {{d_xi_xmax_1_fu_567_p2[14:5]}};

assign tmp_4_fu_622_p4 = {{d_xi_xmax_2_fu_572_p2[14:5]}};

assign tmp_6_fu_647_p4 = {{d_xi_xmax_4_fu_582_p2[14:5]}};

assign tmp_7_fu_662_p4 = {{d_xi_xmax_5_fu_587_p2[14:5]}};

assign tmp_fu_738_p4 = {{add_ln51_4_fu_732_p2[12:8]}};

assign trunc_ln198_1_fu_356_p4 = {{layer6_out_dout[31:16]}};

assign trunc_ln198_2_fu_366_p4 = {{layer6_out_dout[47:32]}};

assign trunc_ln198_3_fu_376_p4 = {{layer6_out_dout[63:48]}};

assign trunc_ln198_4_fu_386_p4 = {{layer6_out_dout[79:64]}};

assign trunc_ln198_5_fu_396_p4 = {{layer6_out_dout[95:80]}};

assign trunc_ln198_fu_352_p1 = layer6_out_dout[15:0];

assign trunc_ln213_fu_458_p1 = layer6_out_dout[14:0];

assign trunc_ln241_1_fu_780_p4 = {{mul_ln241_1_fu_205_p2[25:10]}};

assign trunc_ln241_2_fu_794_p4 = {{mul_ln241_2_fu_202_p2[25:10]}};

assign trunc_ln241_3_fu_808_p4 = {{mul_ln241_3_fu_201_p2[25:10]}};

assign trunc_ln241_4_fu_822_p4 = {{mul_ln241_4_fu_206_p2[25:10]}};

assign trunc_ln241_5_fu_836_p4 = {{mul_ln241_5_fu_203_p2[25:10]}};

assign trunc_ln2_fu_766_p4 = {{mul_ln241_fu_204_p2[25:10]}};

assign trunc_ln66_1_fu_550_p1 = select_ln66_3_fu_528_p3[14:0];

assign trunc_ln66_fu_546_p1 = select_ln66_2_fu_517_p3[14:0];

assign xor_ln66_1_fu_432_p2 = (icmp_ln66_1_fu_426_p2 ^ 1'd1);

assign xor_ln66_2_fu_512_p2 = (icmp_ln66_2_reg_883 ^ 1'd1);

assign xor_ln66_3_fu_523_p2 = (icmp_ln66_3_reg_888 ^ 1'd1);

assign xor_ln66_4_fu_540_p2 = (icmp_ln66_4_fu_534_p2 ^ 1'd1);

assign xor_ln66_fu_412_p2 = (icmp_ln66_fu_406_p2 ^ 1'd1);

assign zext_ln145_1_fu_684_p1 = exp_table_load_1_reg_959;

assign zext_ln145_2_fu_687_p1 = exp_table_load_2_reg_965;

assign zext_ln145_3_fu_690_p1 = exp_table_q0;

assign zext_ln145_4_fu_694_p1 = exp_table_load_4_reg_976;

assign zext_ln145_fu_681_p1 = exp_table_load_reg_953;

assign zext_ln223_1_fu_617_p1 = tmp_3_fu_607_p4;

assign zext_ln223_2_fu_632_p1 = tmp_4_fu_622_p4;

assign zext_ln223_3_fu_677_p1 = tmp_5_reg_938;

assign zext_ln223_4_fu_657_p1 = tmp_6_fu_647_p4;

assign zext_ln223_5_fu_672_p1 = tmp_7_fu_662_p4;

assign zext_ln223_fu_602_p1 = tmp_2_fu_592_p4;

assign zext_ln232_fu_748_p1 = tmp_fu_738_p4;

assign zext_ln51_1_fu_712_p1 = add_ln51_1_fu_706_p2;

assign zext_ln51_2_fu_728_p1 = add_ln51_3_fu_722_p2;

assign zext_ln51_fu_697_p1 = exp_table_load_5_reg_982;

endmodule //myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_6u_softmax_config7_s
